# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cpp_to_py_backend.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'cpp_to_py_backend.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63pp_to_py_backend.proto\"\x1c\n\x04\x45\x64ge\x12\t\n\x01u\x18\x01 \x01(\r\x12\t\n\x01v\x18\x02 \x01(\r\" \n\x08\x45\x64geList\x12\x14\n\x05\x65\x64ges\x18\x01 \x03(\x0b\x32\x05.Edge\"R\n\x13\x43olourHierarchyNode\x12\x0e\n\x06\x63olour\x18\x01 \x01(\r\x12+\n\rchildrenNodes\x18\x02 \x03(\x0b\x32\x14.ColourHierarchyNode\"\x85\x01\n\nPreQAPData\x12\x11\n\tgraphHash\x18\x01 \x01(\t\x12\x31\n\x13\x63olourHierarchyRoot\x18\x02 \x01(\x0b\x32\x14.ColourHierarchyNode\x12\r\n\x05rowsF\x18\x03 \x01(\r\x12\r\n\x05\x63olsF\x18\x04 \x01(\r\x12\x13\n\x0blinearizedF\x18\x05 \x03(\x04\"0\n\x0f\x43olourOrderPair\x12\x0e\n\x06\x63olour\x18\x01 \x01(\r\x12\r\n\x05order\x18\x02 \x01(\r\"J\n\x0bPostQAPData\x12\x11\n\tgraphHash\x18\x01 \x01(\t\x12(\n\x0e\x63olourOrdering\x18\x02 \x03(\x0b\x32\x10.ColourOrderPair\"\'\n\x0f\x43\x61rtesianCoords\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"5\n\x0bGraphLayout\x12&\n\x0cvertexCoords\x18\x01 \x03(\x0b\x32\x10.CartesianCoords2\x87\x01\n\x12GraphLayoutService\x12\x35\n\x19performPreQAPComputations\x12\t.EdgeList\x1a\x0b.PreQAPData\"\x00\x12:\n\x1aperformPostQAPComputations\x12\x0c.PostQAPData\x1a\x0c.GraphLayout\"\x00\x32\x35\n\tQAPSolver\x12(\n\x0bSolvePreQAP\x12\x0b.PreQAPData\x1a\x0c.PostQAPDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cpp_to_py_backend_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EDGE']._serialized_start=27
  _globals['_EDGE']._serialized_end=55
  _globals['_EDGELIST']._serialized_start=57
  _globals['_EDGELIST']._serialized_end=89
  _globals['_COLOURHIERARCHYNODE']._serialized_start=91
  _globals['_COLOURHIERARCHYNODE']._serialized_end=173
  _globals['_PREQAPDATA']._serialized_start=176
  _globals['_PREQAPDATA']._serialized_end=309
  _globals['_COLOURORDERPAIR']._serialized_start=311
  _globals['_COLOURORDERPAIR']._serialized_end=359
  _globals['_POSTQAPDATA']._serialized_start=361
  _globals['_POSTQAPDATA']._serialized_end=435
  _globals['_CARTESIANCOORDS']._serialized_start=437
  _globals['_CARTESIANCOORDS']._serialized_end=476
  _globals['_GRAPHLAYOUT']._serialized_start=478
  _globals['_GRAPHLAYOUT']._serialized_end=531
  _globals['_GRAPHLAYOUTSERVICE']._serialized_start=534
  _globals['_GRAPHLAYOUTSERVICE']._serialized_end=669
  _globals['_QAPSOLVER']._serialized_start=671
  _globals['_QAPSOLVER']._serialized_end=724
# @@protoc_insertion_point(module_scope)
