services:
  backend:
    build: ./app/backend
    ports:
      - "30301-30305:30301-30305"
    volumes:
      - ./app/backend:/app
    stdin_open: true
    tty: true
    networks:
      - dag-app-network

  frontend:
    build: ./app/frontend
    ports:
      - "30306-30310:30306-30310"
    volumes:
      - ./app/frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - dag-app-network
    depends_on:
      - backend

networks:
  dag-app-network:
