services:
  python-backend:
    build: ./app/python-backend
    ports:
      - "30301-30305:30301-30305"
    volumes:
      - ./app/python-backend:/app  
    stdin_open: true
    tty: true  
    networks:
      - dag-app-py-front-network 
      - dag-app-py-cpp-network
    depends_on:
      - cpp-backend  

  frontend:
    build: ./app/frontend
    ports:
      - "30306-30310:30306-30310"
    volumes:
      - ./app/frontend:/app 
      - /app/node_modules
    stdin_open: true
    tty: true    
    networks:
      - dag-app-py-front-network
    depends_on:
      - python-backend 

  cpp-backend: 
    build: ./app/cpp-backend 
    ports:
      - "30311-30315:30311-30315"
    volumes:      
      - ./app/cpp-backend:/app
    stdin_open: true 
    tty: true 
    networks:   
      - dag-app-py-cpp-network    

networks:
  dag-app-py-front-network: 
  dag-app-py-cpp-network:                 