// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/cpp_to_py_backend.proto

#include "cpp_to_py_backend.pb.h"
#include "cpp_to_py_backend.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* GraphLayoutService_method_names[] = {
  "/GraphLayoutService/performPreQAPComputations",
  "/GraphLayoutService/performPostQAPComputations",
};

std::unique_ptr< GraphLayoutService::Stub> GraphLayoutService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GraphLayoutService::Stub> stub(new GraphLayoutService::Stub(channel));
  return stub;
}

GraphLayoutService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_performPreQAPComputations_(GraphLayoutService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_performPostQAPComputations_(GraphLayoutService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status GraphLayoutService::Stub::performPreQAPComputations(::grpc::ClientContext* context, const ::EdgeList& request, ::PreQAPData* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_performPreQAPComputations_, context, request, response);
}

void GraphLayoutService::Stub::experimental_async::performPreQAPComputations(::grpc::ClientContext* context, const ::EdgeList* request, ::PreQAPData* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_performPreQAPComputations_, context, request, response, std::move(f));
}

void GraphLayoutService::Stub::experimental_async::performPreQAPComputations(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::PreQAPData* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_performPreQAPComputations_, context, request, response, std::move(f));
}

void GraphLayoutService::Stub::experimental_async::performPreQAPComputations(::grpc::ClientContext* context, const ::EdgeList* request, ::PreQAPData* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_performPreQAPComputations_, context, request, response, reactor);
}

void GraphLayoutService::Stub::experimental_async::performPreQAPComputations(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::PreQAPData* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_performPreQAPComputations_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::PreQAPData>* GraphLayoutService::Stub::AsyncperformPreQAPComputationsRaw(::grpc::ClientContext* context, const ::EdgeList& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::PreQAPData>::Create(channel_.get(), cq, rpcmethod_performPreQAPComputations_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::PreQAPData>* GraphLayoutService::Stub::PrepareAsyncperformPreQAPComputationsRaw(::grpc::ClientContext* context, const ::EdgeList& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::PreQAPData>::Create(channel_.get(), cq, rpcmethod_performPreQAPComputations_, context, request, false);
}

::grpc::Status GraphLayoutService::Stub::performPostQAPComputations(::grpc::ClientContext* context, const ::PostQAPData& request, ::GraphLayout* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_performPostQAPComputations_, context, request, response);
}

void GraphLayoutService::Stub::experimental_async::performPostQAPComputations(::grpc::ClientContext* context, const ::PostQAPData* request, ::GraphLayout* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_performPostQAPComputations_, context, request, response, std::move(f));
}

void GraphLayoutService::Stub::experimental_async::performPostQAPComputations(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::GraphLayout* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_performPostQAPComputations_, context, request, response, std::move(f));
}

void GraphLayoutService::Stub::experimental_async::performPostQAPComputations(::grpc::ClientContext* context, const ::PostQAPData* request, ::GraphLayout* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_performPostQAPComputations_, context, request, response, reactor);
}

void GraphLayoutService::Stub::experimental_async::performPostQAPComputations(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::GraphLayout* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_performPostQAPComputations_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GraphLayout>* GraphLayoutService::Stub::AsyncperformPostQAPComputationsRaw(::grpc::ClientContext* context, const ::PostQAPData& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::GraphLayout>::Create(channel_.get(), cq, rpcmethod_performPostQAPComputations_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::GraphLayout>* GraphLayoutService::Stub::PrepareAsyncperformPostQAPComputationsRaw(::grpc::ClientContext* context, const ::PostQAPData& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::GraphLayout>::Create(channel_.get(), cq, rpcmethod_performPostQAPComputations_, context, request, false);
}

GraphLayoutService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GraphLayoutService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GraphLayoutService::Service, ::EdgeList, ::PreQAPData>(
          [](GraphLayoutService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::EdgeList* req,
             ::PreQAPData* resp) {
               return service->performPreQAPComputations(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GraphLayoutService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GraphLayoutService::Service, ::PostQAPData, ::GraphLayout>(
          [](GraphLayoutService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::PostQAPData* req,
             ::GraphLayout* resp) {
               return service->performPostQAPComputations(ctx, req, resp);
             }, this)));
}

GraphLayoutService::Service::~Service() {
}

::grpc::Status GraphLayoutService::Service::performPreQAPComputations(::grpc::ServerContext* context, const ::EdgeList* request, ::PreQAPData* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GraphLayoutService::Service::performPostQAPComputations(::grpc::ServerContext* context, const ::PostQAPData* request, ::GraphLayout* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


