// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/cpp_to_py_backend.proto

#include "cpp_to_py_backend.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_proto_2fcpp_5fto_5fpy_5fbackend_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_CartesianCoords_proto_2fcpp_5fto_5fpy_5fbackend_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_proto_2fcpp_5fto_5fpy_5fbackend_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ColourHierarchyNode_proto_2fcpp_5fto_5fpy_5fbackend_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_proto_2fcpp_5fto_5fpy_5fbackend_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ColourOrderPair_proto_2fcpp_5fto_5fpy_5fbackend_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_proto_2fcpp_5fto_5fpy_5fbackend_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Edge_proto_2fcpp_5fto_5fpy_5fbackend_2eproto;
class EdgeDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Edge> _instance;
} _Edge_default_instance_;
class EdgeListDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<EdgeList> _instance;
} _EdgeList_default_instance_;
class ColourHierarchyNodeDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ColourHierarchyNode> _instance;
} _ColourHierarchyNode_default_instance_;
class PreQAPDataDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PreQAPData> _instance;
} _PreQAPData_default_instance_;
class ColourOrderPairDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ColourOrderPair> _instance;
} _ColourOrderPair_default_instance_;
class PostQAPDataDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PostQAPData> _instance;
} _PostQAPData_default_instance_;
class CartesianCoordsDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<CartesianCoords> _instance;
} _CartesianCoords_default_instance_;
class GraphLayoutDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GraphLayout> _instance;
} _GraphLayout_default_instance_;
static void InitDefaultsscc_info_CartesianCoords_proto_2fcpp_5fto_5fpy_5fbackend_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_CartesianCoords_default_instance_;
    new (ptr) ::CartesianCoords();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CartesianCoords::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_CartesianCoords_proto_2fcpp_5fto_5fpy_5fbackend_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_CartesianCoords_proto_2fcpp_5fto_5fpy_5fbackend_2eproto}, {}};

static void InitDefaultsscc_info_ColourHierarchyNode_proto_2fcpp_5fto_5fpy_5fbackend_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_ColourHierarchyNode_default_instance_;
    new (ptr) ::ColourHierarchyNode();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ColourHierarchyNode::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ColourHierarchyNode_proto_2fcpp_5fto_5fpy_5fbackend_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ColourHierarchyNode_proto_2fcpp_5fto_5fpy_5fbackend_2eproto}, {}};

static void InitDefaultsscc_info_ColourOrderPair_proto_2fcpp_5fto_5fpy_5fbackend_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_ColourOrderPair_default_instance_;
    new (ptr) ::ColourOrderPair();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ColourOrderPair::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ColourOrderPair_proto_2fcpp_5fto_5fpy_5fbackend_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ColourOrderPair_proto_2fcpp_5fto_5fpy_5fbackend_2eproto}, {}};

static void InitDefaultsscc_info_Edge_proto_2fcpp_5fto_5fpy_5fbackend_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_Edge_default_instance_;
    new (ptr) ::Edge();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Edge::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Edge_proto_2fcpp_5fto_5fpy_5fbackend_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Edge_proto_2fcpp_5fto_5fpy_5fbackend_2eproto}, {}};

static void InitDefaultsscc_info_EdgeList_proto_2fcpp_5fto_5fpy_5fbackend_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_EdgeList_default_instance_;
    new (ptr) ::EdgeList();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::EdgeList::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_EdgeList_proto_2fcpp_5fto_5fpy_5fbackend_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_EdgeList_proto_2fcpp_5fto_5fpy_5fbackend_2eproto}, {
      &scc_info_Edge_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.base,}};

static void InitDefaultsscc_info_GraphLayout_proto_2fcpp_5fto_5fpy_5fbackend_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_GraphLayout_default_instance_;
    new (ptr) ::GraphLayout();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::GraphLayout::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_GraphLayout_proto_2fcpp_5fto_5fpy_5fbackend_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_GraphLayout_proto_2fcpp_5fto_5fpy_5fbackend_2eproto}, {
      &scc_info_CartesianCoords_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.base,}};

static void InitDefaultsscc_info_PostQAPData_proto_2fcpp_5fto_5fpy_5fbackend_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_PostQAPData_default_instance_;
    new (ptr) ::PostQAPData();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PostQAPData::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_PostQAPData_proto_2fcpp_5fto_5fpy_5fbackend_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_PostQAPData_proto_2fcpp_5fto_5fpy_5fbackend_2eproto}, {
      &scc_info_ColourOrderPair_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.base,}};

static void InitDefaultsscc_info_PreQAPData_proto_2fcpp_5fto_5fpy_5fbackend_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_PreQAPData_default_instance_;
    new (ptr) ::PreQAPData();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PreQAPData::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_PreQAPData_proto_2fcpp_5fto_5fpy_5fbackend_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_PreQAPData_proto_2fcpp_5fto_5fpy_5fbackend_2eproto}, {
      &scc_info_ColourHierarchyNode_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_proto_2fcpp_5fto_5fpy_5fbackend_2eproto[8];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_proto_2fcpp_5fto_5fpy_5fbackend_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_proto_2fcpp_5fto_5fpy_5fbackend_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_proto_2fcpp_5fto_5fpy_5fbackend_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Edge, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Edge, u_),
  PROTOBUF_FIELD_OFFSET(::Edge, v_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::EdgeList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::EdgeList, edges_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ColourHierarchyNode, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ColourHierarchyNode, colour_),
  PROTOBUF_FIELD_OFFSET(::ColourHierarchyNode, childrennodes_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PreQAPData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::PreQAPData, graphhash_),
  PROTOBUF_FIELD_OFFSET(::PreQAPData, colourhierarchyroot_),
  PROTOBUF_FIELD_OFFSET(::PreQAPData, rowsf_),
  PROTOBUF_FIELD_OFFSET(::PreQAPData, colsf_),
  PROTOBUF_FIELD_OFFSET(::PreQAPData, linearizedf_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ColourOrderPair, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ColourOrderPair, colour_),
  PROTOBUF_FIELD_OFFSET(::ColourOrderPair, order_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PostQAPData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::PostQAPData, graphhash_),
  PROTOBUF_FIELD_OFFSET(::PostQAPData, colourordering_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::CartesianCoords, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::CartesianCoords, x_),
  PROTOBUF_FIELD_OFFSET(::CartesianCoords, y_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::GraphLayout, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::GraphLayout, vertexcoords_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Edge)},
  { 7, -1, sizeof(::EdgeList)},
  { 13, -1, sizeof(::ColourHierarchyNode)},
  { 20, -1, sizeof(::PreQAPData)},
  { 30, -1, sizeof(::ColourOrderPair)},
  { 37, -1, sizeof(::PostQAPData)},
  { 44, -1, sizeof(::CartesianCoords)},
  { 51, -1, sizeof(::GraphLayout)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_Edge_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_EdgeList_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_ColourHierarchyNode_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_PreQAPData_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_ColourOrderPair_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_PostQAPData_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_CartesianCoords_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_GraphLayout_default_instance_),
};

const char descriptor_table_protodef_proto_2fcpp_5fto_5fpy_5fbackend_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\035proto/cpp_to_py_backend.proto\"\034\n\004Edge\022"
  "\t\n\001u\030\001 \001(\r\022\t\n\001v\030\002 \001(\r\" \n\010EdgeList\022\024\n\005edg"
  "es\030\001 \003(\0132\005.Edge\"R\n\023ColourHierarchyNode\022\016"
  "\n\006colour\030\001 \001(\r\022+\n\rchildrenNodes\030\002 \003(\0132\024."
  "ColourHierarchyNode\"\205\001\n\nPreQAPData\022\021\n\tgr"
  "aphHash\030\001 \001(\t\0221\n\023colourHierarchyRoot\030\002 \001"
  "(\0132\024.ColourHierarchyNode\022\r\n\005rowsF\030\003 \001(\r\022"
  "\r\n\005colsF\030\004 \001(\r\022\023\n\013linearizedF\030\005 \003(\004\"0\n\017C"
  "olourOrderPair\022\016\n\006colour\030\001 \001(\r\022\r\n\005order\030"
  "\002 \001(\r\"J\n\013PostQAPData\022\021\n\tgraphHash\030\001 \001(\t\022"
  "(\n\016colourOrdering\030\002 \003(\0132\020.ColourOrderPai"
  "r\"\'\n\017CartesianCoords\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001"
  "(\002\"5\n\013GraphLayout\022&\n\014vertexCoords\030\001 \003(\0132"
  "\020.CartesianCoords2\207\001\n\022GraphLayoutService"
  "\0225\n\031performPreQAPComputations\022\t.EdgeList"
  "\032\013.PreQAPData\"\000\022:\n\032performPostQAPComputa"
  "tions\022\014.PostQAPData\032\014.GraphLayout\"\000b\006pro"
  "to3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_proto_2fcpp_5fto_5fpy_5fbackend_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_proto_2fcpp_5fto_5fpy_5fbackend_2eproto_sccs[8] = {
  &scc_info_CartesianCoords_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.base,
  &scc_info_ColourHierarchyNode_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.base,
  &scc_info_ColourOrderPair_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.base,
  &scc_info_Edge_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.base,
  &scc_info_EdgeList_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.base,
  &scc_info_GraphLayout_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.base,
  &scc_info_PostQAPData_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.base,
  &scc_info_PreQAPData_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_proto_2fcpp_5fto_5fpy_5fbackend_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fcpp_5fto_5fpy_5fbackend_2eproto = {
  false, false, descriptor_table_protodef_proto_2fcpp_5fto_5fpy_5fbackend_2eproto, "proto/cpp_to_py_backend.proto", 683,
  &descriptor_table_proto_2fcpp_5fto_5fpy_5fbackend_2eproto_once, descriptor_table_proto_2fcpp_5fto_5fpy_5fbackend_2eproto_sccs, descriptor_table_proto_2fcpp_5fto_5fpy_5fbackend_2eproto_deps, 8, 0,
  schemas, file_default_instances, TableStruct_proto_2fcpp_5fto_5fpy_5fbackend_2eproto::offsets,
  file_level_metadata_proto_2fcpp_5fto_5fpy_5fbackend_2eproto, 8, file_level_enum_descriptors_proto_2fcpp_5fto_5fpy_5fbackend_2eproto, file_level_service_descriptors_proto_2fcpp_5fto_5fpy_5fbackend_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_proto_2fcpp_5fto_5fpy_5fbackend_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_proto_2fcpp_5fto_5fpy_5fbackend_2eproto)), true);

// ===================================================================

void Edge::InitAsDefaultInstance() {
}
class Edge::_Internal {
 public:
};

Edge::Edge(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Edge)
}
Edge::Edge(const Edge& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&u_, &from.u_,
    static_cast<size_t>(reinterpret_cast<char*>(&v_) -
    reinterpret_cast<char*>(&u_)) + sizeof(v_));
  // @@protoc_insertion_point(copy_constructor:Edge)
}

void Edge::SharedCtor() {
  ::memset(&u_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&v_) -
      reinterpret_cast<char*>(&u_)) + sizeof(v_));
}

Edge::~Edge() {
  // @@protoc_insertion_point(destructor:Edge)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Edge::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void Edge::ArenaDtor(void* object) {
  Edge* _this = reinterpret_cast< Edge* >(object);
  (void)_this;
}
void Edge::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Edge::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Edge& Edge::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Edge_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.base);
  return *internal_default_instance();
}


void Edge::Clear() {
// @@protoc_insertion_point(message_clear_start:Edge)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&u_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&v_) -
      reinterpret_cast<char*>(&u_)) + sizeof(v_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Edge::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 u = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          u_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 v = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          v_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Edge::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Edge)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 u = 1;
  if (this->u() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_u(), target);
  }

  // uint32 v = 2;
  if (this->v() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_v(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Edge)
  return target;
}

size_t Edge::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Edge)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 u = 1;
  if (this->u() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_u());
  }

  // uint32 v = 2;
  if (this->v() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_v());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Edge::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Edge)
  GOOGLE_DCHECK_NE(&from, this);
  const Edge* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Edge>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Edge)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Edge)
    MergeFrom(*source);
  }
}

void Edge::MergeFrom(const Edge& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Edge)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.u() != 0) {
    _internal_set_u(from._internal_u());
  }
  if (from.v() != 0) {
    _internal_set_v(from._internal_v());
  }
}

void Edge::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Edge)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Edge::CopyFrom(const Edge& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Edge)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Edge::IsInitialized() const {
  return true;
}

void Edge::InternalSwap(Edge* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Edge, v_)
      + sizeof(Edge::v_)
      - PROTOBUF_FIELD_OFFSET(Edge, u_)>(
          reinterpret_cast<char*>(&u_),
          reinterpret_cast<char*>(&other->u_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Edge::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void EdgeList::InitAsDefaultInstance() {
}
class EdgeList::_Internal {
 public:
};

EdgeList::EdgeList(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  edges_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:EdgeList)
}
EdgeList::EdgeList(const EdgeList& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      edges_(from.edges_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:EdgeList)
}

void EdgeList::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_EdgeList_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.base);
}

EdgeList::~EdgeList() {
  // @@protoc_insertion_point(destructor:EdgeList)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void EdgeList::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void EdgeList::ArenaDtor(void* object) {
  EdgeList* _this = reinterpret_cast< EdgeList* >(object);
  (void)_this;
}
void EdgeList::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void EdgeList::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const EdgeList& EdgeList::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_EdgeList_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.base);
  return *internal_default_instance();
}


void EdgeList::Clear() {
// @@protoc_insertion_point(message_clear_start:EdgeList)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  edges_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* EdgeList::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .Edge edges = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_edges(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* EdgeList::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:EdgeList)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Edge edges = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_edges_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_edges(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:EdgeList)
  return target;
}

size_t EdgeList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:EdgeList)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Edge edges = 1;
  total_size += 1UL * this->_internal_edges_size();
  for (const auto& msg : this->edges_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void EdgeList::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:EdgeList)
  GOOGLE_DCHECK_NE(&from, this);
  const EdgeList* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<EdgeList>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:EdgeList)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:EdgeList)
    MergeFrom(*source);
  }
}

void EdgeList::MergeFrom(const EdgeList& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:EdgeList)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  edges_.MergeFrom(from.edges_);
}

void EdgeList::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:EdgeList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EdgeList::CopyFrom(const EdgeList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:EdgeList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EdgeList::IsInitialized() const {
  return true;
}

void EdgeList::InternalSwap(EdgeList* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  edges_.InternalSwap(&other->edges_);
}

::PROTOBUF_NAMESPACE_ID::Metadata EdgeList::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ColourHierarchyNode::InitAsDefaultInstance() {
}
class ColourHierarchyNode::_Internal {
 public:
};

ColourHierarchyNode::ColourHierarchyNode(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  childrennodes_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:ColourHierarchyNode)
}
ColourHierarchyNode::ColourHierarchyNode(const ColourHierarchyNode& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      childrennodes_(from.childrennodes_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  colour_ = from.colour_;
  // @@protoc_insertion_point(copy_constructor:ColourHierarchyNode)
}

void ColourHierarchyNode::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ColourHierarchyNode_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.base);
  colour_ = 0u;
}

ColourHierarchyNode::~ColourHierarchyNode() {
  // @@protoc_insertion_point(destructor:ColourHierarchyNode)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ColourHierarchyNode::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void ColourHierarchyNode::ArenaDtor(void* object) {
  ColourHierarchyNode* _this = reinterpret_cast< ColourHierarchyNode* >(object);
  (void)_this;
}
void ColourHierarchyNode::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ColourHierarchyNode::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ColourHierarchyNode& ColourHierarchyNode::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ColourHierarchyNode_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.base);
  return *internal_default_instance();
}


void ColourHierarchyNode::Clear() {
// @@protoc_insertion_point(message_clear_start:ColourHierarchyNode)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  childrennodes_.Clear();
  colour_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ColourHierarchyNode::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 colour = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          colour_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .ColourHierarchyNode childrenNodes = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_childrennodes(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ColourHierarchyNode::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ColourHierarchyNode)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 colour = 1;
  if (this->colour() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_colour(), target);
  }

  // repeated .ColourHierarchyNode childrenNodes = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_childrennodes_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_childrennodes(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ColourHierarchyNode)
  return target;
}

size_t ColourHierarchyNode::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ColourHierarchyNode)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .ColourHierarchyNode childrenNodes = 2;
  total_size += 1UL * this->_internal_childrennodes_size();
  for (const auto& msg : this->childrennodes_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint32 colour = 1;
  if (this->colour() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_colour());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ColourHierarchyNode::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ColourHierarchyNode)
  GOOGLE_DCHECK_NE(&from, this);
  const ColourHierarchyNode* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ColourHierarchyNode>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ColourHierarchyNode)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ColourHierarchyNode)
    MergeFrom(*source);
  }
}

void ColourHierarchyNode::MergeFrom(const ColourHierarchyNode& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ColourHierarchyNode)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  childrennodes_.MergeFrom(from.childrennodes_);
  if (from.colour() != 0) {
    _internal_set_colour(from._internal_colour());
  }
}

void ColourHierarchyNode::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ColourHierarchyNode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ColourHierarchyNode::CopyFrom(const ColourHierarchyNode& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ColourHierarchyNode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ColourHierarchyNode::IsInitialized() const {
  return true;
}

void ColourHierarchyNode::InternalSwap(ColourHierarchyNode* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  childrennodes_.InternalSwap(&other->childrennodes_);
  swap(colour_, other->colour_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ColourHierarchyNode::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void PreQAPData::InitAsDefaultInstance() {
  ::_PreQAPData_default_instance_._instance.get_mutable()->colourhierarchyroot_ = const_cast< ::ColourHierarchyNode*>(
      ::ColourHierarchyNode::internal_default_instance());
}
class PreQAPData::_Internal {
 public:
  static const ::ColourHierarchyNode& colourhierarchyroot(const PreQAPData* msg);
};

const ::ColourHierarchyNode&
PreQAPData::_Internal::colourhierarchyroot(const PreQAPData* msg) {
  return *msg->colourhierarchyroot_;
}
PreQAPData::PreQAPData(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  linearizedf_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:PreQAPData)
}
PreQAPData::PreQAPData(const PreQAPData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      linearizedf_(from.linearizedf_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  graphhash_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_graphhash().empty()) {
    graphhash_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_graphhash(),
      GetArena());
  }
  if (from._internal_has_colourhierarchyroot()) {
    colourhierarchyroot_ = new ::ColourHierarchyNode(*from.colourhierarchyroot_);
  } else {
    colourhierarchyroot_ = nullptr;
  }
  ::memcpy(&rowsf_, &from.rowsf_,
    static_cast<size_t>(reinterpret_cast<char*>(&colsf_) -
    reinterpret_cast<char*>(&rowsf_)) + sizeof(colsf_));
  // @@protoc_insertion_point(copy_constructor:PreQAPData)
}

void PreQAPData::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_PreQAPData_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.base);
  graphhash_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&colourhierarchyroot_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&colsf_) -
      reinterpret_cast<char*>(&colourhierarchyroot_)) + sizeof(colsf_));
}

PreQAPData::~PreQAPData() {
  // @@protoc_insertion_point(destructor:PreQAPData)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void PreQAPData::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  graphhash_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete colourhierarchyroot_;
}

void PreQAPData::ArenaDtor(void* object) {
  PreQAPData* _this = reinterpret_cast< PreQAPData* >(object);
  (void)_this;
}
void PreQAPData::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PreQAPData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PreQAPData& PreQAPData::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PreQAPData_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.base);
  return *internal_default_instance();
}


void PreQAPData::Clear() {
// @@protoc_insertion_point(message_clear_start:PreQAPData)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  linearizedf_.Clear();
  graphhash_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  if (GetArena() == nullptr && colourhierarchyroot_ != nullptr) {
    delete colourhierarchyroot_;
  }
  colourhierarchyroot_ = nullptr;
  ::memset(&rowsf_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&colsf_) -
      reinterpret_cast<char*>(&rowsf_)) + sizeof(colsf_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PreQAPData::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string graphHash = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_graphhash();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "PreQAPData.graphHash"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .ColourHierarchyNode colourHierarchyRoot = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_colourhierarchyroot(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 rowsF = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          rowsf_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 colsF = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          colsf_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated uint64 linearizedF = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt64Parser(_internal_mutable_linearizedf(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40) {
          _internal_add_linearizedf(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PreQAPData::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PreQAPData)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string graphHash = 1;
  if (this->graphhash().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_graphhash().data(), static_cast<int>(this->_internal_graphhash().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PreQAPData.graphHash");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_graphhash(), target);
  }

  // .ColourHierarchyNode colourHierarchyRoot = 2;
  if (this->has_colourhierarchyroot()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::colourhierarchyroot(this), target, stream);
  }

  // uint32 rowsF = 3;
  if (this->rowsf() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_rowsf(), target);
  }

  // uint32 colsF = 4;
  if (this->colsf() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(4, this->_internal_colsf(), target);
  }

  // repeated uint64 linearizedF = 5;
  {
    int byte_size = _linearizedf_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteUInt64Packed(
          5, _internal_linearizedf(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PreQAPData)
  return target;
}

size_t PreQAPData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PreQAPData)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated uint64 linearizedF = 5;
  {
    size_t data_size = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      UInt64Size(this->linearizedf_);
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _linearizedf_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // string graphHash = 1;
  if (this->graphhash().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_graphhash());
  }

  // .ColourHierarchyNode colourHierarchyRoot = 2;
  if (this->has_colourhierarchyroot()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *colourhierarchyroot_);
  }

  // uint32 rowsF = 3;
  if (this->rowsf() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_rowsf());
  }

  // uint32 colsF = 4;
  if (this->colsf() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_colsf());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PreQAPData::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PreQAPData)
  GOOGLE_DCHECK_NE(&from, this);
  const PreQAPData* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PreQAPData>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PreQAPData)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PreQAPData)
    MergeFrom(*source);
  }
}

void PreQAPData::MergeFrom(const PreQAPData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PreQAPData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  linearizedf_.MergeFrom(from.linearizedf_);
  if (from.graphhash().size() > 0) {
    _internal_set_graphhash(from._internal_graphhash());
  }
  if (from.has_colourhierarchyroot()) {
    _internal_mutable_colourhierarchyroot()->::ColourHierarchyNode::MergeFrom(from._internal_colourhierarchyroot());
  }
  if (from.rowsf() != 0) {
    _internal_set_rowsf(from._internal_rowsf());
  }
  if (from.colsf() != 0) {
    _internal_set_colsf(from._internal_colsf());
  }
}

void PreQAPData::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PreQAPData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PreQAPData::CopyFrom(const PreQAPData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PreQAPData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PreQAPData::IsInitialized() const {
  return true;
}

void PreQAPData::InternalSwap(PreQAPData* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  linearizedf_.InternalSwap(&other->linearizedf_);
  graphhash_.Swap(&other->graphhash_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PreQAPData, colsf_)
      + sizeof(PreQAPData::colsf_)
      - PROTOBUF_FIELD_OFFSET(PreQAPData, colourhierarchyroot_)>(
          reinterpret_cast<char*>(&colourhierarchyroot_),
          reinterpret_cast<char*>(&other->colourhierarchyroot_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PreQAPData::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ColourOrderPair::InitAsDefaultInstance() {
}
class ColourOrderPair::_Internal {
 public:
};

ColourOrderPair::ColourOrderPair(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:ColourOrderPair)
}
ColourOrderPair::ColourOrderPair(const ColourOrderPair& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&colour_, &from.colour_,
    static_cast<size_t>(reinterpret_cast<char*>(&order_) -
    reinterpret_cast<char*>(&colour_)) + sizeof(order_));
  // @@protoc_insertion_point(copy_constructor:ColourOrderPair)
}

void ColourOrderPair::SharedCtor() {
  ::memset(&colour_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&order_) -
      reinterpret_cast<char*>(&colour_)) + sizeof(order_));
}

ColourOrderPair::~ColourOrderPair() {
  // @@protoc_insertion_point(destructor:ColourOrderPair)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ColourOrderPair::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void ColourOrderPair::ArenaDtor(void* object) {
  ColourOrderPair* _this = reinterpret_cast< ColourOrderPair* >(object);
  (void)_this;
}
void ColourOrderPair::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ColourOrderPair::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ColourOrderPair& ColourOrderPair::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ColourOrderPair_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.base);
  return *internal_default_instance();
}


void ColourOrderPair::Clear() {
// @@protoc_insertion_point(message_clear_start:ColourOrderPair)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&colour_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&order_) -
      reinterpret_cast<char*>(&colour_)) + sizeof(order_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ColourOrderPair::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 colour = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          colour_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 order = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          order_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ColourOrderPair::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ColourOrderPair)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 colour = 1;
  if (this->colour() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_colour(), target);
  }

  // uint32 order = 2;
  if (this->order() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_order(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ColourOrderPair)
  return target;
}

size_t ColourOrderPair::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ColourOrderPair)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 colour = 1;
  if (this->colour() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_colour());
  }

  // uint32 order = 2;
  if (this->order() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_order());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ColourOrderPair::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ColourOrderPair)
  GOOGLE_DCHECK_NE(&from, this);
  const ColourOrderPair* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ColourOrderPair>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ColourOrderPair)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ColourOrderPair)
    MergeFrom(*source);
  }
}

void ColourOrderPair::MergeFrom(const ColourOrderPair& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ColourOrderPair)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.colour() != 0) {
    _internal_set_colour(from._internal_colour());
  }
  if (from.order() != 0) {
    _internal_set_order(from._internal_order());
  }
}

void ColourOrderPair::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ColourOrderPair)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ColourOrderPair::CopyFrom(const ColourOrderPair& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ColourOrderPair)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ColourOrderPair::IsInitialized() const {
  return true;
}

void ColourOrderPair::InternalSwap(ColourOrderPair* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ColourOrderPair, order_)
      + sizeof(ColourOrderPair::order_)
      - PROTOBUF_FIELD_OFFSET(ColourOrderPair, colour_)>(
          reinterpret_cast<char*>(&colour_),
          reinterpret_cast<char*>(&other->colour_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ColourOrderPair::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void PostQAPData::InitAsDefaultInstance() {
}
class PostQAPData::_Internal {
 public:
};

PostQAPData::PostQAPData(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  colourordering_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:PostQAPData)
}
PostQAPData::PostQAPData(const PostQAPData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      colourordering_(from.colourordering_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  graphhash_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_graphhash().empty()) {
    graphhash_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_graphhash(),
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:PostQAPData)
}

void PostQAPData::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_PostQAPData_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.base);
  graphhash_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

PostQAPData::~PostQAPData() {
  // @@protoc_insertion_point(destructor:PostQAPData)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void PostQAPData::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  graphhash_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void PostQAPData::ArenaDtor(void* object) {
  PostQAPData* _this = reinterpret_cast< PostQAPData* >(object);
  (void)_this;
}
void PostQAPData::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PostQAPData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PostQAPData& PostQAPData::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PostQAPData_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.base);
  return *internal_default_instance();
}


void PostQAPData::Clear() {
// @@protoc_insertion_point(message_clear_start:PostQAPData)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  colourordering_.Clear();
  graphhash_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PostQAPData::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string graphHash = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_graphhash();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "PostQAPData.graphHash"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .ColourOrderPair colourOrdering = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_colourordering(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PostQAPData::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PostQAPData)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string graphHash = 1;
  if (this->graphhash().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_graphhash().data(), static_cast<int>(this->_internal_graphhash().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PostQAPData.graphHash");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_graphhash(), target);
  }

  // repeated .ColourOrderPair colourOrdering = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_colourordering_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_colourordering(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PostQAPData)
  return target;
}

size_t PostQAPData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PostQAPData)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .ColourOrderPair colourOrdering = 2;
  total_size += 1UL * this->_internal_colourordering_size();
  for (const auto& msg : this->colourordering_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string graphHash = 1;
  if (this->graphhash().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_graphhash());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PostQAPData::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PostQAPData)
  GOOGLE_DCHECK_NE(&from, this);
  const PostQAPData* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PostQAPData>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PostQAPData)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PostQAPData)
    MergeFrom(*source);
  }
}

void PostQAPData::MergeFrom(const PostQAPData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PostQAPData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  colourordering_.MergeFrom(from.colourordering_);
  if (from.graphhash().size() > 0) {
    _internal_set_graphhash(from._internal_graphhash());
  }
}

void PostQAPData::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PostQAPData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PostQAPData::CopyFrom(const PostQAPData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PostQAPData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PostQAPData::IsInitialized() const {
  return true;
}

void PostQAPData::InternalSwap(PostQAPData* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  colourordering_.InternalSwap(&other->colourordering_);
  graphhash_.Swap(&other->graphhash_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata PostQAPData::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void CartesianCoords::InitAsDefaultInstance() {
}
class CartesianCoords::_Internal {
 public:
};

CartesianCoords::CartesianCoords(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:CartesianCoords)
}
CartesianCoords::CartesianCoords(const CartesianCoords& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&y_) -
    reinterpret_cast<char*>(&x_)) + sizeof(y_));
  // @@protoc_insertion_point(copy_constructor:CartesianCoords)
}

void CartesianCoords::SharedCtor() {
  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&y_) -
      reinterpret_cast<char*>(&x_)) + sizeof(y_));
}

CartesianCoords::~CartesianCoords() {
  // @@protoc_insertion_point(destructor:CartesianCoords)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void CartesianCoords::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void CartesianCoords::ArenaDtor(void* object) {
  CartesianCoords* _this = reinterpret_cast< CartesianCoords* >(object);
  (void)_this;
}
void CartesianCoords::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void CartesianCoords::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CartesianCoords& CartesianCoords::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_CartesianCoords_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.base);
  return *internal_default_instance();
}


void CartesianCoords::Clear() {
// @@protoc_insertion_point(message_clear_start:CartesianCoords)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&y_) -
      reinterpret_cast<char*>(&x_)) + sizeof(y_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CartesianCoords::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // float x = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 13)) {
          x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float y = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21)) {
          y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* CartesianCoords::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CartesianCoords)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  if (!(this->x() <= 0 && this->x() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(1, this->_internal_x(), target);
  }

  // float y = 2;
  if (!(this->y() <= 0 && this->y() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(2, this->_internal_y(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CartesianCoords)
  return target;
}

size_t CartesianCoords::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CartesianCoords)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float x = 1;
  if (!(this->x() <= 0 && this->x() >= 0)) {
    total_size += 1 + 4;
  }

  // float y = 2;
  if (!(this->y() <= 0 && this->y() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CartesianCoords::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CartesianCoords)
  GOOGLE_DCHECK_NE(&from, this);
  const CartesianCoords* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<CartesianCoords>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CartesianCoords)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CartesianCoords)
    MergeFrom(*source);
  }
}

void CartesianCoords::MergeFrom(const CartesianCoords& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CartesianCoords)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!(from.x() <= 0 && from.x() >= 0)) {
    _internal_set_x(from._internal_x());
  }
  if (!(from.y() <= 0 && from.y() >= 0)) {
    _internal_set_y(from._internal_y());
  }
}

void CartesianCoords::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CartesianCoords)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CartesianCoords::CopyFrom(const CartesianCoords& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CartesianCoords)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CartesianCoords::IsInitialized() const {
  return true;
}

void CartesianCoords::InternalSwap(CartesianCoords* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CartesianCoords, y_)
      + sizeof(CartesianCoords::y_)
      - PROTOBUF_FIELD_OFFSET(CartesianCoords, x_)>(
          reinterpret_cast<char*>(&x_),
          reinterpret_cast<char*>(&other->x_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CartesianCoords::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void GraphLayout::InitAsDefaultInstance() {
}
class GraphLayout::_Internal {
 public:
};

GraphLayout::GraphLayout(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  vertexcoords_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:GraphLayout)
}
GraphLayout::GraphLayout(const GraphLayout& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      vertexcoords_(from.vertexcoords_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:GraphLayout)
}

void GraphLayout::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_GraphLayout_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.base);
}

GraphLayout::~GraphLayout() {
  // @@protoc_insertion_point(destructor:GraphLayout)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GraphLayout::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void GraphLayout::ArenaDtor(void* object) {
  GraphLayout* _this = reinterpret_cast< GraphLayout* >(object);
  (void)_this;
}
void GraphLayout::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GraphLayout::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GraphLayout& GraphLayout::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GraphLayout_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.base);
  return *internal_default_instance();
}


void GraphLayout::Clear() {
// @@protoc_insertion_point(message_clear_start:GraphLayout)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  vertexcoords_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GraphLayout::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .CartesianCoords vertexCoords = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_vertexcoords(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GraphLayout::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GraphLayout)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .CartesianCoords vertexCoords = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_vertexcoords_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_vertexcoords(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GraphLayout)
  return target;
}

size_t GraphLayout::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GraphLayout)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .CartesianCoords vertexCoords = 1;
  total_size += 1UL * this->_internal_vertexcoords_size();
  for (const auto& msg : this->vertexcoords_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GraphLayout::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:GraphLayout)
  GOOGLE_DCHECK_NE(&from, this);
  const GraphLayout* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GraphLayout>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:GraphLayout)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:GraphLayout)
    MergeFrom(*source);
  }
}

void GraphLayout::MergeFrom(const GraphLayout& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:GraphLayout)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  vertexcoords_.MergeFrom(from.vertexcoords_);
}

void GraphLayout::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:GraphLayout)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GraphLayout::CopyFrom(const GraphLayout& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GraphLayout)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GraphLayout::IsInitialized() const {
  return true;
}

void GraphLayout::InternalSwap(GraphLayout* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  vertexcoords_.InternalSwap(&other->vertexcoords_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GraphLayout::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Edge* Arena::CreateMaybeMessage< ::Edge >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Edge >(arena);
}
template<> PROTOBUF_NOINLINE ::EdgeList* Arena::CreateMaybeMessage< ::EdgeList >(Arena* arena) {
  return Arena::CreateMessageInternal< ::EdgeList >(arena);
}
template<> PROTOBUF_NOINLINE ::ColourHierarchyNode* Arena::CreateMaybeMessage< ::ColourHierarchyNode >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ColourHierarchyNode >(arena);
}
template<> PROTOBUF_NOINLINE ::PreQAPData* Arena::CreateMaybeMessage< ::PreQAPData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PreQAPData >(arena);
}
template<> PROTOBUF_NOINLINE ::ColourOrderPair* Arena::CreateMaybeMessage< ::ColourOrderPair >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ColourOrderPair >(arena);
}
template<> PROTOBUF_NOINLINE ::PostQAPData* Arena::CreateMaybeMessage< ::PostQAPData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PostQAPData >(arena);
}
template<> PROTOBUF_NOINLINE ::CartesianCoords* Arena::CreateMaybeMessage< ::CartesianCoords >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CartesianCoords >(arena);
}
template<> PROTOBUF_NOINLINE ::GraphLayout* Arena::CreateMaybeMessage< ::GraphLayout >(Arena* arena) {
  return Arena::CreateMessageInternal< ::GraphLayout >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
