// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/cpp_to_py_backend.proto
#ifndef GRPC_proto_2fcpp_5fto_5fpy_5fbackend_2eproto__INCLUDED
#define GRPC_proto_2fcpp_5fto_5fpy_5fbackend_2eproto__INCLUDED

#include "cpp_to_py_backend.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

class GraphLayoutService final {
 public:
  static constexpr char const* service_full_name() {
    return "GraphLayoutService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status performPreQAPComputations(::grpc::ClientContext* context, const ::EdgeList& request, ::PreQAPData* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PreQAPData>> AsyncperformPreQAPComputations(::grpc::ClientContext* context, const ::EdgeList& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PreQAPData>>(AsyncperformPreQAPComputationsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PreQAPData>> PrepareAsyncperformPreQAPComputations(::grpc::ClientContext* context, const ::EdgeList& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PreQAPData>>(PrepareAsyncperformPreQAPComputationsRaw(context, request, cq));
    }
    virtual ::grpc::Status performPostQAPComputations(::grpc::ClientContext* context, const ::PostQAPData& request, ::GraphLayout* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GraphLayout>> AsyncperformPostQAPComputations(::grpc::ClientContext* context, const ::PostQAPData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GraphLayout>>(AsyncperformPostQAPComputationsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GraphLayout>> PrepareAsyncperformPostQAPComputations(::grpc::ClientContext* context, const ::PostQAPData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GraphLayout>>(PrepareAsyncperformPostQAPComputationsRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void performPreQAPComputations(::grpc::ClientContext* context, const ::EdgeList* request, ::PreQAPData* response, std::function<void(::grpc::Status)>) = 0;
      virtual void performPreQAPComputations(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::PreQAPData* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void performPreQAPComputations(::grpc::ClientContext* context, const ::EdgeList* request, ::PreQAPData* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void performPreQAPComputations(::grpc::ClientContext* context, const ::EdgeList* request, ::PreQAPData* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void performPreQAPComputations(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::PreQAPData* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void performPreQAPComputations(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::PreQAPData* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void performPostQAPComputations(::grpc::ClientContext* context, const ::PostQAPData* request, ::GraphLayout* response, std::function<void(::grpc::Status)>) = 0;
      virtual void performPostQAPComputations(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::GraphLayout* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void performPostQAPComputations(::grpc::ClientContext* context, const ::PostQAPData* request, ::GraphLayout* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void performPostQAPComputations(::grpc::ClientContext* context, const ::PostQAPData* request, ::GraphLayout* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void performPostQAPComputations(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::GraphLayout* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void performPostQAPComputations(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::GraphLayout* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::PreQAPData>* AsyncperformPreQAPComputationsRaw(::grpc::ClientContext* context, const ::EdgeList& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::PreQAPData>* PrepareAsyncperformPreQAPComputationsRaw(::grpc::ClientContext* context, const ::EdgeList& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GraphLayout>* AsyncperformPostQAPComputationsRaw(::grpc::ClientContext* context, const ::PostQAPData& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GraphLayout>* PrepareAsyncperformPostQAPComputationsRaw(::grpc::ClientContext* context, const ::PostQAPData& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status performPreQAPComputations(::grpc::ClientContext* context, const ::EdgeList& request, ::PreQAPData* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PreQAPData>> AsyncperformPreQAPComputations(::grpc::ClientContext* context, const ::EdgeList& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PreQAPData>>(AsyncperformPreQAPComputationsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PreQAPData>> PrepareAsyncperformPreQAPComputations(::grpc::ClientContext* context, const ::EdgeList& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PreQAPData>>(PrepareAsyncperformPreQAPComputationsRaw(context, request, cq));
    }
    ::grpc::Status performPostQAPComputations(::grpc::ClientContext* context, const ::PostQAPData& request, ::GraphLayout* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GraphLayout>> AsyncperformPostQAPComputations(::grpc::ClientContext* context, const ::PostQAPData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GraphLayout>>(AsyncperformPostQAPComputationsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GraphLayout>> PrepareAsyncperformPostQAPComputations(::grpc::ClientContext* context, const ::PostQAPData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GraphLayout>>(PrepareAsyncperformPostQAPComputationsRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void performPreQAPComputations(::grpc::ClientContext* context, const ::EdgeList* request, ::PreQAPData* response, std::function<void(::grpc::Status)>) override;
      void performPreQAPComputations(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::PreQAPData* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void performPreQAPComputations(::grpc::ClientContext* context, const ::EdgeList* request, ::PreQAPData* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void performPreQAPComputations(::grpc::ClientContext* context, const ::EdgeList* request, ::PreQAPData* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void performPreQAPComputations(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::PreQAPData* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void performPreQAPComputations(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::PreQAPData* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void performPostQAPComputations(::grpc::ClientContext* context, const ::PostQAPData* request, ::GraphLayout* response, std::function<void(::grpc::Status)>) override;
      void performPostQAPComputations(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::GraphLayout* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void performPostQAPComputations(::grpc::ClientContext* context, const ::PostQAPData* request, ::GraphLayout* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void performPostQAPComputations(::grpc::ClientContext* context, const ::PostQAPData* request, ::GraphLayout* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void performPostQAPComputations(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::GraphLayout* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void performPostQAPComputations(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::GraphLayout* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::PreQAPData>* AsyncperformPreQAPComputationsRaw(::grpc::ClientContext* context, const ::EdgeList& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::PreQAPData>* PrepareAsyncperformPreQAPComputationsRaw(::grpc::ClientContext* context, const ::EdgeList& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::GraphLayout>* AsyncperformPostQAPComputationsRaw(::grpc::ClientContext* context, const ::PostQAPData& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::GraphLayout>* PrepareAsyncperformPostQAPComputationsRaw(::grpc::ClientContext* context, const ::PostQAPData& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_performPreQAPComputations_;
    const ::grpc::internal::RpcMethod rpcmethod_performPostQAPComputations_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status performPreQAPComputations(::grpc::ServerContext* context, const ::EdgeList* request, ::PreQAPData* response);
    virtual ::grpc::Status performPostQAPComputations(::grpc::ServerContext* context, const ::PostQAPData* request, ::GraphLayout* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_performPreQAPComputations : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_performPreQAPComputations() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_performPreQAPComputations() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status performPreQAPComputations(::grpc::ServerContext* /*context*/, const ::EdgeList* /*request*/, ::PreQAPData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestperformPreQAPComputations(::grpc::ServerContext* context, ::EdgeList* request, ::grpc::ServerAsyncResponseWriter< ::PreQAPData>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_performPostQAPComputations : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_performPostQAPComputations() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_performPostQAPComputations() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status performPostQAPComputations(::grpc::ServerContext* /*context*/, const ::PostQAPData* /*request*/, ::GraphLayout* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestperformPostQAPComputations(::grpc::ServerContext* context, ::PostQAPData* request, ::grpc::ServerAsyncResponseWriter< ::GraphLayout>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_performPreQAPComputations<WithAsyncMethod_performPostQAPComputations<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_performPreQAPComputations : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_performPreQAPComputations() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::EdgeList, ::PreQAPData>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::EdgeList* request, ::PreQAPData* response) { return this->performPreQAPComputations(context, request, response); }));}
    void SetMessageAllocatorFor_performPreQAPComputations(
        ::grpc::experimental::MessageAllocator< ::EdgeList, ::PreQAPData>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::EdgeList, ::PreQAPData>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_performPreQAPComputations() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status performPreQAPComputations(::grpc::ServerContext* /*context*/, const ::EdgeList* /*request*/, ::PreQAPData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* performPreQAPComputations(
      ::grpc::CallbackServerContext* /*context*/, const ::EdgeList* /*request*/, ::PreQAPData* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* performPreQAPComputations(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::EdgeList* /*request*/, ::PreQAPData* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_performPostQAPComputations : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_performPostQAPComputations() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::PostQAPData, ::GraphLayout>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::PostQAPData* request, ::GraphLayout* response) { return this->performPostQAPComputations(context, request, response); }));}
    void SetMessageAllocatorFor_performPostQAPComputations(
        ::grpc::experimental::MessageAllocator< ::PostQAPData, ::GraphLayout>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::PostQAPData, ::GraphLayout>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_performPostQAPComputations() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status performPostQAPComputations(::grpc::ServerContext* /*context*/, const ::PostQAPData* /*request*/, ::GraphLayout* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* performPostQAPComputations(
      ::grpc::CallbackServerContext* /*context*/, const ::PostQAPData* /*request*/, ::GraphLayout* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* performPostQAPComputations(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::PostQAPData* /*request*/, ::GraphLayout* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_performPreQAPComputations<ExperimentalWithCallbackMethod_performPostQAPComputations<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_performPreQAPComputations<ExperimentalWithCallbackMethod_performPostQAPComputations<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_performPreQAPComputations : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_performPreQAPComputations() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_performPreQAPComputations() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status performPreQAPComputations(::grpc::ServerContext* /*context*/, const ::EdgeList* /*request*/, ::PreQAPData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_performPostQAPComputations : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_performPostQAPComputations() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_performPostQAPComputations() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status performPostQAPComputations(::grpc::ServerContext* /*context*/, const ::PostQAPData* /*request*/, ::GraphLayout* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_performPreQAPComputations : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_performPreQAPComputations() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_performPreQAPComputations() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status performPreQAPComputations(::grpc::ServerContext* /*context*/, const ::EdgeList* /*request*/, ::PreQAPData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestperformPreQAPComputations(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_performPostQAPComputations : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_performPostQAPComputations() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_performPostQAPComputations() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status performPostQAPComputations(::grpc::ServerContext* /*context*/, const ::PostQAPData* /*request*/, ::GraphLayout* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestperformPostQAPComputations(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_performPreQAPComputations : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_performPreQAPComputations() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->performPreQAPComputations(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_performPreQAPComputations() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status performPreQAPComputations(::grpc::ServerContext* /*context*/, const ::EdgeList* /*request*/, ::PreQAPData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* performPreQAPComputations(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* performPreQAPComputations(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_performPostQAPComputations : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_performPostQAPComputations() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->performPostQAPComputations(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_performPostQAPComputations() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status performPostQAPComputations(::grpc::ServerContext* /*context*/, const ::PostQAPData* /*request*/, ::GraphLayout* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* performPostQAPComputations(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* performPostQAPComputations(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_performPreQAPComputations : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_performPreQAPComputations() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::EdgeList, ::PreQAPData>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::EdgeList, ::PreQAPData>* streamer) {
                       return this->StreamedperformPreQAPComputations(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_performPreQAPComputations() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status performPreQAPComputations(::grpc::ServerContext* /*context*/, const ::EdgeList* /*request*/, ::PreQAPData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedperformPreQAPComputations(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::EdgeList,::PreQAPData>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_performPostQAPComputations : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_performPostQAPComputations() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::PostQAPData, ::GraphLayout>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::PostQAPData, ::GraphLayout>* streamer) {
                       return this->StreamedperformPostQAPComputations(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_performPostQAPComputations() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status performPostQAPComputations(::grpc::ServerContext* /*context*/, const ::PostQAPData* /*request*/, ::GraphLayout* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedperformPostQAPComputations(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::PostQAPData,::GraphLayout>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_performPreQAPComputations<WithStreamedUnaryMethod_performPostQAPComputations<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_performPreQAPComputations<WithStreamedUnaryMethod_performPostQAPComputations<Service > > StreamedService;
};


#endif  // GRPC_proto_2fcpp_5fto_5fpy_5fbackend_2eproto__INCLUDED
