// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/cpp_to_py_backend.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2fcpp_5fto_5fpy_5fbackend_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2fcpp_5fto_5fpy_5fbackend_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2fcpp_5fto_5fpy_5fbackend_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fcpp_5fto_5fpy_5fbackend_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[8]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fcpp_5fto_5fpy_5fbackend_2eproto;
class CartesianCoords;
class CartesianCoordsDefaultTypeInternal;
extern CartesianCoordsDefaultTypeInternal _CartesianCoords_default_instance_;
class ColourHierarchyNode;
class ColourHierarchyNodeDefaultTypeInternal;
extern ColourHierarchyNodeDefaultTypeInternal _ColourHierarchyNode_default_instance_;
class ColourOrderPair;
class ColourOrderPairDefaultTypeInternal;
extern ColourOrderPairDefaultTypeInternal _ColourOrderPair_default_instance_;
class Edge;
class EdgeDefaultTypeInternal;
extern EdgeDefaultTypeInternal _Edge_default_instance_;
class EdgeList;
class EdgeListDefaultTypeInternal;
extern EdgeListDefaultTypeInternal _EdgeList_default_instance_;
class GraphLayout;
class GraphLayoutDefaultTypeInternal;
extern GraphLayoutDefaultTypeInternal _GraphLayout_default_instance_;
class PostQAPData;
class PostQAPDataDefaultTypeInternal;
extern PostQAPDataDefaultTypeInternal _PostQAPData_default_instance_;
class PreQAPData;
class PreQAPDataDefaultTypeInternal;
extern PreQAPDataDefaultTypeInternal _PreQAPData_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::CartesianCoords* Arena::CreateMaybeMessage<::CartesianCoords>(Arena*);
template<> ::ColourHierarchyNode* Arena::CreateMaybeMessage<::ColourHierarchyNode>(Arena*);
template<> ::ColourOrderPair* Arena::CreateMaybeMessage<::ColourOrderPair>(Arena*);
template<> ::Edge* Arena::CreateMaybeMessage<::Edge>(Arena*);
template<> ::EdgeList* Arena::CreateMaybeMessage<::EdgeList>(Arena*);
template<> ::GraphLayout* Arena::CreateMaybeMessage<::GraphLayout>(Arena*);
template<> ::PostQAPData* Arena::CreateMaybeMessage<::PostQAPData>(Arena*);
template<> ::PreQAPData* Arena::CreateMaybeMessage<::PreQAPData>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Edge PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Edge) */ {
 public:
  inline Edge() : Edge(nullptr) {};
  virtual ~Edge();

  Edge(const Edge& from);
  Edge(Edge&& from) noexcept
    : Edge() {
    *this = ::std::move(from);
  }

  inline Edge& operator=(const Edge& from) {
    CopyFrom(from);
    return *this;
  }
  inline Edge& operator=(Edge&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Edge& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Edge* internal_default_instance() {
    return reinterpret_cast<const Edge*>(
               &_Edge_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Edge& a, Edge& b) {
    a.Swap(&b);
  }
  inline void Swap(Edge* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Edge* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Edge* New() const final {
    return CreateMaybeMessage<Edge>(nullptr);
  }

  Edge* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Edge>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Edge& from);
  void MergeFrom(const Edge& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Edge* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Edge";
  }
  protected:
  explicit Edge(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2fcpp_5fto_5fpy_5fbackend_2eproto);
    return ::descriptor_table_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUFieldNumber = 1,
    kVFieldNumber = 2,
  };
  // uint32 u = 1;
  void clear_u();
  ::PROTOBUF_NAMESPACE_ID::uint32 u() const;
  void set_u(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_u() const;
  void _internal_set_u(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 v = 2;
  void clear_v();
  ::PROTOBUF_NAMESPACE_ID::uint32 v() const;
  void set_v(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_v() const;
  void _internal_set_v(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:Edge)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 u_;
  ::PROTOBUF_NAMESPACE_ID::uint32 v_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fcpp_5fto_5fpy_5fbackend_2eproto;
};
// -------------------------------------------------------------------

class EdgeList PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:EdgeList) */ {
 public:
  inline EdgeList() : EdgeList(nullptr) {};
  virtual ~EdgeList();

  EdgeList(const EdgeList& from);
  EdgeList(EdgeList&& from) noexcept
    : EdgeList() {
    *this = ::std::move(from);
  }

  inline EdgeList& operator=(const EdgeList& from) {
    CopyFrom(from);
    return *this;
  }
  inline EdgeList& operator=(EdgeList&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EdgeList& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EdgeList* internal_default_instance() {
    return reinterpret_cast<const EdgeList*>(
               &_EdgeList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(EdgeList& a, EdgeList& b) {
    a.Swap(&b);
  }
  inline void Swap(EdgeList* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EdgeList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EdgeList* New() const final {
    return CreateMaybeMessage<EdgeList>(nullptr);
  }

  EdgeList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EdgeList>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EdgeList& from);
  void MergeFrom(const EdgeList& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EdgeList* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "EdgeList";
  }
  protected:
  explicit EdgeList(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2fcpp_5fto_5fpy_5fbackend_2eproto);
    return ::descriptor_table_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEdgesFieldNumber = 1,
  };
  // repeated .Edge edges = 1;
  int edges_size() const;
  private:
  int _internal_edges_size() const;
  public:
  void clear_edges();
  ::Edge* mutable_edges(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Edge >*
      mutable_edges();
  private:
  const ::Edge& _internal_edges(int index) const;
  ::Edge* _internal_add_edges();
  public:
  const ::Edge& edges(int index) const;
  ::Edge* add_edges();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Edge >&
      edges() const;

  // @@protoc_insertion_point(class_scope:EdgeList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Edge > edges_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fcpp_5fto_5fpy_5fbackend_2eproto;
};
// -------------------------------------------------------------------

class ColourHierarchyNode PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ColourHierarchyNode) */ {
 public:
  inline ColourHierarchyNode() : ColourHierarchyNode(nullptr) {};
  virtual ~ColourHierarchyNode();

  ColourHierarchyNode(const ColourHierarchyNode& from);
  ColourHierarchyNode(ColourHierarchyNode&& from) noexcept
    : ColourHierarchyNode() {
    *this = ::std::move(from);
  }

  inline ColourHierarchyNode& operator=(const ColourHierarchyNode& from) {
    CopyFrom(from);
    return *this;
  }
  inline ColourHierarchyNode& operator=(ColourHierarchyNode&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ColourHierarchyNode& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ColourHierarchyNode* internal_default_instance() {
    return reinterpret_cast<const ColourHierarchyNode*>(
               &_ColourHierarchyNode_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ColourHierarchyNode& a, ColourHierarchyNode& b) {
    a.Swap(&b);
  }
  inline void Swap(ColourHierarchyNode* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ColourHierarchyNode* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ColourHierarchyNode* New() const final {
    return CreateMaybeMessage<ColourHierarchyNode>(nullptr);
  }

  ColourHierarchyNode* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ColourHierarchyNode>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ColourHierarchyNode& from);
  void MergeFrom(const ColourHierarchyNode& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ColourHierarchyNode* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ColourHierarchyNode";
  }
  protected:
  explicit ColourHierarchyNode(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2fcpp_5fto_5fpy_5fbackend_2eproto);
    return ::descriptor_table_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kChildrenNodesFieldNumber = 2,
    kColourFieldNumber = 1,
  };
  // repeated .ColourHierarchyNode childrenNodes = 2;
  int childrennodes_size() const;
  private:
  int _internal_childrennodes_size() const;
  public:
  void clear_childrennodes();
  ::ColourHierarchyNode* mutable_childrennodes(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ColourHierarchyNode >*
      mutable_childrennodes();
  private:
  const ::ColourHierarchyNode& _internal_childrennodes(int index) const;
  ::ColourHierarchyNode* _internal_add_childrennodes();
  public:
  const ::ColourHierarchyNode& childrennodes(int index) const;
  ::ColourHierarchyNode* add_childrennodes();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ColourHierarchyNode >&
      childrennodes() const;

  // uint32 colour = 1;
  void clear_colour();
  ::PROTOBUF_NAMESPACE_ID::uint32 colour() const;
  void set_colour(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_colour() const;
  void _internal_set_colour(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:ColourHierarchyNode)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ColourHierarchyNode > childrennodes_;
  ::PROTOBUF_NAMESPACE_ID::uint32 colour_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fcpp_5fto_5fpy_5fbackend_2eproto;
};
// -------------------------------------------------------------------

class PreQAPData PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PreQAPData) */ {
 public:
  inline PreQAPData() : PreQAPData(nullptr) {};
  virtual ~PreQAPData();

  PreQAPData(const PreQAPData& from);
  PreQAPData(PreQAPData&& from) noexcept
    : PreQAPData() {
    *this = ::std::move(from);
  }

  inline PreQAPData& operator=(const PreQAPData& from) {
    CopyFrom(from);
    return *this;
  }
  inline PreQAPData& operator=(PreQAPData&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PreQAPData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PreQAPData* internal_default_instance() {
    return reinterpret_cast<const PreQAPData*>(
               &_PreQAPData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PreQAPData& a, PreQAPData& b) {
    a.Swap(&b);
  }
  inline void Swap(PreQAPData* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PreQAPData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PreQAPData* New() const final {
    return CreateMaybeMessage<PreQAPData>(nullptr);
  }

  PreQAPData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PreQAPData>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PreQAPData& from);
  void MergeFrom(const PreQAPData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PreQAPData* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PreQAPData";
  }
  protected:
  explicit PreQAPData(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2fcpp_5fto_5fpy_5fbackend_2eproto);
    return ::descriptor_table_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLinearizedFFieldNumber = 5,
    kGraphHashFieldNumber = 1,
    kColourHierarchyRootFieldNumber = 2,
    kRowsFFieldNumber = 3,
    kColsFFieldNumber = 4,
  };
  // repeated uint64 linearizedF = 5;
  int linearizedf_size() const;
  private:
  int _internal_linearizedf_size() const;
  public:
  void clear_linearizedf();
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_linearizedf(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
      _internal_linearizedf() const;
  void _internal_add_linearizedf(::PROTOBUF_NAMESPACE_ID::uint64 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
      _internal_mutable_linearizedf();
  public:
  ::PROTOBUF_NAMESPACE_ID::uint64 linearizedf(int index) const;
  void set_linearizedf(int index, ::PROTOBUF_NAMESPACE_ID::uint64 value);
  void add_linearizedf(::PROTOBUF_NAMESPACE_ID::uint64 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
      linearizedf() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
      mutable_linearizedf();

  // string graphHash = 1;
  void clear_graphhash();
  const std::string& graphhash() const;
  void set_graphhash(const std::string& value);
  void set_graphhash(std::string&& value);
  void set_graphhash(const char* value);
  void set_graphhash(const char* value, size_t size);
  std::string* mutable_graphhash();
  std::string* release_graphhash();
  void set_allocated_graphhash(std::string* graphhash);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_graphhash();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_graphhash(
      std::string* graphhash);
  private:
  const std::string& _internal_graphhash() const;
  void _internal_set_graphhash(const std::string& value);
  std::string* _internal_mutable_graphhash();
  public:

  // .ColourHierarchyNode colourHierarchyRoot = 2;
  bool has_colourhierarchyroot() const;
  private:
  bool _internal_has_colourhierarchyroot() const;
  public:
  void clear_colourhierarchyroot();
  const ::ColourHierarchyNode& colourhierarchyroot() const;
  ::ColourHierarchyNode* release_colourhierarchyroot();
  ::ColourHierarchyNode* mutable_colourhierarchyroot();
  void set_allocated_colourhierarchyroot(::ColourHierarchyNode* colourhierarchyroot);
  private:
  const ::ColourHierarchyNode& _internal_colourhierarchyroot() const;
  ::ColourHierarchyNode* _internal_mutable_colourhierarchyroot();
  public:
  void unsafe_arena_set_allocated_colourhierarchyroot(
      ::ColourHierarchyNode* colourhierarchyroot);
  ::ColourHierarchyNode* unsafe_arena_release_colourhierarchyroot();

  // uint32 rowsF = 3;
  void clear_rowsf();
  ::PROTOBUF_NAMESPACE_ID::uint32 rowsf() const;
  void set_rowsf(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_rowsf() const;
  void _internal_set_rowsf(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 colsF = 4;
  void clear_colsf();
  ::PROTOBUF_NAMESPACE_ID::uint32 colsf() const;
  void set_colsf(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_colsf() const;
  void _internal_set_colsf(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:PreQAPData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 > linearizedf_;
  mutable std::atomic<int> _linearizedf_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr graphhash_;
  ::ColourHierarchyNode* colourhierarchyroot_;
  ::PROTOBUF_NAMESPACE_ID::uint32 rowsf_;
  ::PROTOBUF_NAMESPACE_ID::uint32 colsf_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fcpp_5fto_5fpy_5fbackend_2eproto;
};
// -------------------------------------------------------------------

class ColourOrderPair PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ColourOrderPair) */ {
 public:
  inline ColourOrderPair() : ColourOrderPair(nullptr) {};
  virtual ~ColourOrderPair();

  ColourOrderPair(const ColourOrderPair& from);
  ColourOrderPair(ColourOrderPair&& from) noexcept
    : ColourOrderPair() {
    *this = ::std::move(from);
  }

  inline ColourOrderPair& operator=(const ColourOrderPair& from) {
    CopyFrom(from);
    return *this;
  }
  inline ColourOrderPair& operator=(ColourOrderPair&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ColourOrderPair& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ColourOrderPair* internal_default_instance() {
    return reinterpret_cast<const ColourOrderPair*>(
               &_ColourOrderPair_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ColourOrderPair& a, ColourOrderPair& b) {
    a.Swap(&b);
  }
  inline void Swap(ColourOrderPair* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ColourOrderPair* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ColourOrderPair* New() const final {
    return CreateMaybeMessage<ColourOrderPair>(nullptr);
  }

  ColourOrderPair* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ColourOrderPair>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ColourOrderPair& from);
  void MergeFrom(const ColourOrderPair& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ColourOrderPair* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ColourOrderPair";
  }
  protected:
  explicit ColourOrderPair(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2fcpp_5fto_5fpy_5fbackend_2eproto);
    return ::descriptor_table_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kColourFieldNumber = 1,
    kOrderFieldNumber = 2,
  };
  // uint32 colour = 1;
  void clear_colour();
  ::PROTOBUF_NAMESPACE_ID::uint32 colour() const;
  void set_colour(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_colour() const;
  void _internal_set_colour(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 order = 2;
  void clear_order();
  ::PROTOBUF_NAMESPACE_ID::uint32 order() const;
  void set_order(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_order() const;
  void _internal_set_order(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:ColourOrderPair)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 colour_;
  ::PROTOBUF_NAMESPACE_ID::uint32 order_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fcpp_5fto_5fpy_5fbackend_2eproto;
};
// -------------------------------------------------------------------

class PostQAPData PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PostQAPData) */ {
 public:
  inline PostQAPData() : PostQAPData(nullptr) {};
  virtual ~PostQAPData();

  PostQAPData(const PostQAPData& from);
  PostQAPData(PostQAPData&& from) noexcept
    : PostQAPData() {
    *this = ::std::move(from);
  }

  inline PostQAPData& operator=(const PostQAPData& from) {
    CopyFrom(from);
    return *this;
  }
  inline PostQAPData& operator=(PostQAPData&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PostQAPData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PostQAPData* internal_default_instance() {
    return reinterpret_cast<const PostQAPData*>(
               &_PostQAPData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(PostQAPData& a, PostQAPData& b) {
    a.Swap(&b);
  }
  inline void Swap(PostQAPData* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PostQAPData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PostQAPData* New() const final {
    return CreateMaybeMessage<PostQAPData>(nullptr);
  }

  PostQAPData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PostQAPData>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PostQAPData& from);
  void MergeFrom(const PostQAPData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PostQAPData* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PostQAPData";
  }
  protected:
  explicit PostQAPData(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2fcpp_5fto_5fpy_5fbackend_2eproto);
    return ::descriptor_table_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kColourOrderingFieldNumber = 2,
    kGraphHashFieldNumber = 1,
  };
  // repeated .ColourOrderPair colourOrdering = 2;
  int colourordering_size() const;
  private:
  int _internal_colourordering_size() const;
  public:
  void clear_colourordering();
  ::ColourOrderPair* mutable_colourordering(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ColourOrderPair >*
      mutable_colourordering();
  private:
  const ::ColourOrderPair& _internal_colourordering(int index) const;
  ::ColourOrderPair* _internal_add_colourordering();
  public:
  const ::ColourOrderPair& colourordering(int index) const;
  ::ColourOrderPair* add_colourordering();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ColourOrderPair >&
      colourordering() const;

  // string graphHash = 1;
  void clear_graphhash();
  const std::string& graphhash() const;
  void set_graphhash(const std::string& value);
  void set_graphhash(std::string&& value);
  void set_graphhash(const char* value);
  void set_graphhash(const char* value, size_t size);
  std::string* mutable_graphhash();
  std::string* release_graphhash();
  void set_allocated_graphhash(std::string* graphhash);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_graphhash();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_graphhash(
      std::string* graphhash);
  private:
  const std::string& _internal_graphhash() const;
  void _internal_set_graphhash(const std::string& value);
  std::string* _internal_mutable_graphhash();
  public:

  // @@protoc_insertion_point(class_scope:PostQAPData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ColourOrderPair > colourordering_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr graphhash_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fcpp_5fto_5fpy_5fbackend_2eproto;
};
// -------------------------------------------------------------------

class CartesianCoords PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CartesianCoords) */ {
 public:
  inline CartesianCoords() : CartesianCoords(nullptr) {};
  virtual ~CartesianCoords();

  CartesianCoords(const CartesianCoords& from);
  CartesianCoords(CartesianCoords&& from) noexcept
    : CartesianCoords() {
    *this = ::std::move(from);
  }

  inline CartesianCoords& operator=(const CartesianCoords& from) {
    CopyFrom(from);
    return *this;
  }
  inline CartesianCoords& operator=(CartesianCoords&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CartesianCoords& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CartesianCoords* internal_default_instance() {
    return reinterpret_cast<const CartesianCoords*>(
               &_CartesianCoords_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(CartesianCoords& a, CartesianCoords& b) {
    a.Swap(&b);
  }
  inline void Swap(CartesianCoords* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CartesianCoords* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CartesianCoords* New() const final {
    return CreateMaybeMessage<CartesianCoords>(nullptr);
  }

  CartesianCoords* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CartesianCoords>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CartesianCoords& from);
  void MergeFrom(const CartesianCoords& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CartesianCoords* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CartesianCoords";
  }
  protected:
  explicit CartesianCoords(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2fcpp_5fto_5fpy_5fbackend_2eproto);
    return ::descriptor_table_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // @@protoc_insertion_point(class_scope:CartesianCoords)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float x_;
  float y_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fcpp_5fto_5fpy_5fbackend_2eproto;
};
// -------------------------------------------------------------------

class GraphLayout PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GraphLayout) */ {
 public:
  inline GraphLayout() : GraphLayout(nullptr) {};
  virtual ~GraphLayout();

  GraphLayout(const GraphLayout& from);
  GraphLayout(GraphLayout&& from) noexcept
    : GraphLayout() {
    *this = ::std::move(from);
  }

  inline GraphLayout& operator=(const GraphLayout& from) {
    CopyFrom(from);
    return *this;
  }
  inline GraphLayout& operator=(GraphLayout&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GraphLayout& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GraphLayout* internal_default_instance() {
    return reinterpret_cast<const GraphLayout*>(
               &_GraphLayout_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(GraphLayout& a, GraphLayout& b) {
    a.Swap(&b);
  }
  inline void Swap(GraphLayout* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GraphLayout* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GraphLayout* New() const final {
    return CreateMaybeMessage<GraphLayout>(nullptr);
  }

  GraphLayout* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GraphLayout>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GraphLayout& from);
  void MergeFrom(const GraphLayout& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GraphLayout* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GraphLayout";
  }
  protected:
  explicit GraphLayout(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2fcpp_5fto_5fpy_5fbackend_2eproto);
    return ::descriptor_table_proto_2fcpp_5fto_5fpy_5fbackend_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVertexCoordsFieldNumber = 1,
  };
  // repeated .CartesianCoords vertexCoords = 1;
  int vertexcoords_size() const;
  private:
  int _internal_vertexcoords_size() const;
  public:
  void clear_vertexcoords();
  ::CartesianCoords* mutable_vertexcoords(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CartesianCoords >*
      mutable_vertexcoords();
  private:
  const ::CartesianCoords& _internal_vertexcoords(int index) const;
  ::CartesianCoords* _internal_add_vertexcoords();
  public:
  const ::CartesianCoords& vertexcoords(int index) const;
  ::CartesianCoords* add_vertexcoords();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CartesianCoords >&
      vertexcoords() const;

  // @@protoc_insertion_point(class_scope:GraphLayout)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CartesianCoords > vertexcoords_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fcpp_5fto_5fpy_5fbackend_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Edge

// uint32 u = 1;
inline void Edge::clear_u() {
  u_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Edge::_internal_u() const {
  return u_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Edge::u() const {
  // @@protoc_insertion_point(field_get:Edge.u)
  return _internal_u();
}
inline void Edge::_internal_set_u(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  u_ = value;
}
inline void Edge::set_u(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_u(value);
  // @@protoc_insertion_point(field_set:Edge.u)
}

// uint32 v = 2;
inline void Edge::clear_v() {
  v_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Edge::_internal_v() const {
  return v_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Edge::v() const {
  // @@protoc_insertion_point(field_get:Edge.v)
  return _internal_v();
}
inline void Edge::_internal_set_v(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  v_ = value;
}
inline void Edge::set_v(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_v(value);
  // @@protoc_insertion_point(field_set:Edge.v)
}

// -------------------------------------------------------------------

// EdgeList

// repeated .Edge edges = 1;
inline int EdgeList::_internal_edges_size() const {
  return edges_.size();
}
inline int EdgeList::edges_size() const {
  return _internal_edges_size();
}
inline void EdgeList::clear_edges() {
  edges_.Clear();
}
inline ::Edge* EdgeList::mutable_edges(int index) {
  // @@protoc_insertion_point(field_mutable:EdgeList.edges)
  return edges_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Edge >*
EdgeList::mutable_edges() {
  // @@protoc_insertion_point(field_mutable_list:EdgeList.edges)
  return &edges_;
}
inline const ::Edge& EdgeList::_internal_edges(int index) const {
  return edges_.Get(index);
}
inline const ::Edge& EdgeList::edges(int index) const {
  // @@protoc_insertion_point(field_get:EdgeList.edges)
  return _internal_edges(index);
}
inline ::Edge* EdgeList::_internal_add_edges() {
  return edges_.Add();
}
inline ::Edge* EdgeList::add_edges() {
  // @@protoc_insertion_point(field_add:EdgeList.edges)
  return _internal_add_edges();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Edge >&
EdgeList::edges() const {
  // @@protoc_insertion_point(field_list:EdgeList.edges)
  return edges_;
}

// -------------------------------------------------------------------

// ColourHierarchyNode

// uint32 colour = 1;
inline void ColourHierarchyNode::clear_colour() {
  colour_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ColourHierarchyNode::_internal_colour() const {
  return colour_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ColourHierarchyNode::colour() const {
  // @@protoc_insertion_point(field_get:ColourHierarchyNode.colour)
  return _internal_colour();
}
inline void ColourHierarchyNode::_internal_set_colour(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  colour_ = value;
}
inline void ColourHierarchyNode::set_colour(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_colour(value);
  // @@protoc_insertion_point(field_set:ColourHierarchyNode.colour)
}

// repeated .ColourHierarchyNode childrenNodes = 2;
inline int ColourHierarchyNode::_internal_childrennodes_size() const {
  return childrennodes_.size();
}
inline int ColourHierarchyNode::childrennodes_size() const {
  return _internal_childrennodes_size();
}
inline void ColourHierarchyNode::clear_childrennodes() {
  childrennodes_.Clear();
}
inline ::ColourHierarchyNode* ColourHierarchyNode::mutable_childrennodes(int index) {
  // @@protoc_insertion_point(field_mutable:ColourHierarchyNode.childrenNodes)
  return childrennodes_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ColourHierarchyNode >*
ColourHierarchyNode::mutable_childrennodes() {
  // @@protoc_insertion_point(field_mutable_list:ColourHierarchyNode.childrenNodes)
  return &childrennodes_;
}
inline const ::ColourHierarchyNode& ColourHierarchyNode::_internal_childrennodes(int index) const {
  return childrennodes_.Get(index);
}
inline const ::ColourHierarchyNode& ColourHierarchyNode::childrennodes(int index) const {
  // @@protoc_insertion_point(field_get:ColourHierarchyNode.childrenNodes)
  return _internal_childrennodes(index);
}
inline ::ColourHierarchyNode* ColourHierarchyNode::_internal_add_childrennodes() {
  return childrennodes_.Add();
}
inline ::ColourHierarchyNode* ColourHierarchyNode::add_childrennodes() {
  // @@protoc_insertion_point(field_add:ColourHierarchyNode.childrenNodes)
  return _internal_add_childrennodes();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ColourHierarchyNode >&
ColourHierarchyNode::childrennodes() const {
  // @@protoc_insertion_point(field_list:ColourHierarchyNode.childrenNodes)
  return childrennodes_;
}

// -------------------------------------------------------------------

// PreQAPData

// string graphHash = 1;
inline void PreQAPData::clear_graphhash() {
  graphhash_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PreQAPData::graphhash() const {
  // @@protoc_insertion_point(field_get:PreQAPData.graphHash)
  return _internal_graphhash();
}
inline void PreQAPData::set_graphhash(const std::string& value) {
  _internal_set_graphhash(value);
  // @@protoc_insertion_point(field_set:PreQAPData.graphHash)
}
inline std::string* PreQAPData::mutable_graphhash() {
  // @@protoc_insertion_point(field_mutable:PreQAPData.graphHash)
  return _internal_mutable_graphhash();
}
inline const std::string& PreQAPData::_internal_graphhash() const {
  return graphhash_.Get();
}
inline void PreQAPData::_internal_set_graphhash(const std::string& value) {
  
  graphhash_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PreQAPData::set_graphhash(std::string&& value) {
  
  graphhash_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PreQAPData.graphHash)
}
inline void PreQAPData::set_graphhash(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  graphhash_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PreQAPData.graphHash)
}
inline void PreQAPData::set_graphhash(const char* value,
    size_t size) {
  
  graphhash_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PreQAPData.graphHash)
}
inline std::string* PreQAPData::_internal_mutable_graphhash() {
  
  return graphhash_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PreQAPData::release_graphhash() {
  // @@protoc_insertion_point(field_release:PreQAPData.graphHash)
  return graphhash_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PreQAPData::set_allocated_graphhash(std::string* graphhash) {
  if (graphhash != nullptr) {
    
  } else {
    
  }
  graphhash_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), graphhash,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PreQAPData.graphHash)
}
inline std::string* PreQAPData::unsafe_arena_release_graphhash() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PreQAPData.graphHash)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return graphhash_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PreQAPData::unsafe_arena_set_allocated_graphhash(
    std::string* graphhash) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (graphhash != nullptr) {
    
  } else {
    
  }
  graphhash_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      graphhash, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PreQAPData.graphHash)
}

// .ColourHierarchyNode colourHierarchyRoot = 2;
inline bool PreQAPData::_internal_has_colourhierarchyroot() const {
  return this != internal_default_instance() && colourhierarchyroot_ != nullptr;
}
inline bool PreQAPData::has_colourhierarchyroot() const {
  return _internal_has_colourhierarchyroot();
}
inline void PreQAPData::clear_colourhierarchyroot() {
  if (GetArena() == nullptr && colourhierarchyroot_ != nullptr) {
    delete colourhierarchyroot_;
  }
  colourhierarchyroot_ = nullptr;
}
inline const ::ColourHierarchyNode& PreQAPData::_internal_colourhierarchyroot() const {
  const ::ColourHierarchyNode* p = colourhierarchyroot_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ColourHierarchyNode*>(
      &::_ColourHierarchyNode_default_instance_);
}
inline const ::ColourHierarchyNode& PreQAPData::colourhierarchyroot() const {
  // @@protoc_insertion_point(field_get:PreQAPData.colourHierarchyRoot)
  return _internal_colourhierarchyroot();
}
inline void PreQAPData::unsafe_arena_set_allocated_colourhierarchyroot(
    ::ColourHierarchyNode* colourhierarchyroot) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(colourhierarchyroot_);
  }
  colourhierarchyroot_ = colourhierarchyroot;
  if (colourhierarchyroot) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PreQAPData.colourHierarchyRoot)
}
inline ::ColourHierarchyNode* PreQAPData::release_colourhierarchyroot() {
  auto temp = unsafe_arena_release_colourhierarchyroot();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::ColourHierarchyNode* PreQAPData::unsafe_arena_release_colourhierarchyroot() {
  // @@protoc_insertion_point(field_release:PreQAPData.colourHierarchyRoot)
  
  ::ColourHierarchyNode* temp = colourhierarchyroot_;
  colourhierarchyroot_ = nullptr;
  return temp;
}
inline ::ColourHierarchyNode* PreQAPData::_internal_mutable_colourhierarchyroot() {
  
  if (colourhierarchyroot_ == nullptr) {
    auto* p = CreateMaybeMessage<::ColourHierarchyNode>(GetArena());
    colourhierarchyroot_ = p;
  }
  return colourhierarchyroot_;
}
inline ::ColourHierarchyNode* PreQAPData::mutable_colourhierarchyroot() {
  // @@protoc_insertion_point(field_mutable:PreQAPData.colourHierarchyRoot)
  return _internal_mutable_colourhierarchyroot();
}
inline void PreQAPData::set_allocated_colourhierarchyroot(::ColourHierarchyNode* colourhierarchyroot) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete colourhierarchyroot_;
  }
  if (colourhierarchyroot) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(colourhierarchyroot);
    if (message_arena != submessage_arena) {
      colourhierarchyroot = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, colourhierarchyroot, submessage_arena);
    }
    
  } else {
    
  }
  colourhierarchyroot_ = colourhierarchyroot;
  // @@protoc_insertion_point(field_set_allocated:PreQAPData.colourHierarchyRoot)
}

// uint32 rowsF = 3;
inline void PreQAPData::clear_rowsf() {
  rowsf_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PreQAPData::_internal_rowsf() const {
  return rowsf_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PreQAPData::rowsf() const {
  // @@protoc_insertion_point(field_get:PreQAPData.rowsF)
  return _internal_rowsf();
}
inline void PreQAPData::_internal_set_rowsf(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  rowsf_ = value;
}
inline void PreQAPData::set_rowsf(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_rowsf(value);
  // @@protoc_insertion_point(field_set:PreQAPData.rowsF)
}

// uint32 colsF = 4;
inline void PreQAPData::clear_colsf() {
  colsf_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PreQAPData::_internal_colsf() const {
  return colsf_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PreQAPData::colsf() const {
  // @@protoc_insertion_point(field_get:PreQAPData.colsF)
  return _internal_colsf();
}
inline void PreQAPData::_internal_set_colsf(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  colsf_ = value;
}
inline void PreQAPData::set_colsf(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_colsf(value);
  // @@protoc_insertion_point(field_set:PreQAPData.colsF)
}

// repeated uint64 linearizedF = 5;
inline int PreQAPData::_internal_linearizedf_size() const {
  return linearizedf_.size();
}
inline int PreQAPData::linearizedf_size() const {
  return _internal_linearizedf_size();
}
inline void PreQAPData::clear_linearizedf() {
  linearizedf_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PreQAPData::_internal_linearizedf(int index) const {
  return linearizedf_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PreQAPData::linearizedf(int index) const {
  // @@protoc_insertion_point(field_get:PreQAPData.linearizedF)
  return _internal_linearizedf(index);
}
inline void PreQAPData::set_linearizedf(int index, ::PROTOBUF_NAMESPACE_ID::uint64 value) {
  linearizedf_.Set(index, value);
  // @@protoc_insertion_point(field_set:PreQAPData.linearizedF)
}
inline void PreQAPData::_internal_add_linearizedf(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  linearizedf_.Add(value);
}
inline void PreQAPData::add_linearizedf(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_add_linearizedf(value);
  // @@protoc_insertion_point(field_add:PreQAPData.linearizedF)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
PreQAPData::_internal_linearizedf() const {
  return linearizedf_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
PreQAPData::linearizedf() const {
  // @@protoc_insertion_point(field_list:PreQAPData.linearizedF)
  return _internal_linearizedf();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
PreQAPData::_internal_mutable_linearizedf() {
  return &linearizedf_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
PreQAPData::mutable_linearizedf() {
  // @@protoc_insertion_point(field_mutable_list:PreQAPData.linearizedF)
  return _internal_mutable_linearizedf();
}

// -------------------------------------------------------------------

// ColourOrderPair

// uint32 colour = 1;
inline void ColourOrderPair::clear_colour() {
  colour_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ColourOrderPair::_internal_colour() const {
  return colour_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ColourOrderPair::colour() const {
  // @@protoc_insertion_point(field_get:ColourOrderPair.colour)
  return _internal_colour();
}
inline void ColourOrderPair::_internal_set_colour(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  colour_ = value;
}
inline void ColourOrderPair::set_colour(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_colour(value);
  // @@protoc_insertion_point(field_set:ColourOrderPair.colour)
}

// uint32 order = 2;
inline void ColourOrderPair::clear_order() {
  order_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ColourOrderPair::_internal_order() const {
  return order_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ColourOrderPair::order() const {
  // @@protoc_insertion_point(field_get:ColourOrderPair.order)
  return _internal_order();
}
inline void ColourOrderPair::_internal_set_order(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  order_ = value;
}
inline void ColourOrderPair::set_order(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_order(value);
  // @@protoc_insertion_point(field_set:ColourOrderPair.order)
}

// -------------------------------------------------------------------

// PostQAPData

// string graphHash = 1;
inline void PostQAPData::clear_graphhash() {
  graphhash_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PostQAPData::graphhash() const {
  // @@protoc_insertion_point(field_get:PostQAPData.graphHash)
  return _internal_graphhash();
}
inline void PostQAPData::set_graphhash(const std::string& value) {
  _internal_set_graphhash(value);
  // @@protoc_insertion_point(field_set:PostQAPData.graphHash)
}
inline std::string* PostQAPData::mutable_graphhash() {
  // @@protoc_insertion_point(field_mutable:PostQAPData.graphHash)
  return _internal_mutable_graphhash();
}
inline const std::string& PostQAPData::_internal_graphhash() const {
  return graphhash_.Get();
}
inline void PostQAPData::_internal_set_graphhash(const std::string& value) {
  
  graphhash_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PostQAPData::set_graphhash(std::string&& value) {
  
  graphhash_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PostQAPData.graphHash)
}
inline void PostQAPData::set_graphhash(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  graphhash_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PostQAPData.graphHash)
}
inline void PostQAPData::set_graphhash(const char* value,
    size_t size) {
  
  graphhash_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PostQAPData.graphHash)
}
inline std::string* PostQAPData::_internal_mutable_graphhash() {
  
  return graphhash_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PostQAPData::release_graphhash() {
  // @@protoc_insertion_point(field_release:PostQAPData.graphHash)
  return graphhash_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PostQAPData::set_allocated_graphhash(std::string* graphhash) {
  if (graphhash != nullptr) {
    
  } else {
    
  }
  graphhash_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), graphhash,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PostQAPData.graphHash)
}
inline std::string* PostQAPData::unsafe_arena_release_graphhash() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PostQAPData.graphHash)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return graphhash_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PostQAPData::unsafe_arena_set_allocated_graphhash(
    std::string* graphhash) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (graphhash != nullptr) {
    
  } else {
    
  }
  graphhash_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      graphhash, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PostQAPData.graphHash)
}

// repeated .ColourOrderPair colourOrdering = 2;
inline int PostQAPData::_internal_colourordering_size() const {
  return colourordering_.size();
}
inline int PostQAPData::colourordering_size() const {
  return _internal_colourordering_size();
}
inline void PostQAPData::clear_colourordering() {
  colourordering_.Clear();
}
inline ::ColourOrderPair* PostQAPData::mutable_colourordering(int index) {
  // @@protoc_insertion_point(field_mutable:PostQAPData.colourOrdering)
  return colourordering_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ColourOrderPair >*
PostQAPData::mutable_colourordering() {
  // @@protoc_insertion_point(field_mutable_list:PostQAPData.colourOrdering)
  return &colourordering_;
}
inline const ::ColourOrderPair& PostQAPData::_internal_colourordering(int index) const {
  return colourordering_.Get(index);
}
inline const ::ColourOrderPair& PostQAPData::colourordering(int index) const {
  // @@protoc_insertion_point(field_get:PostQAPData.colourOrdering)
  return _internal_colourordering(index);
}
inline ::ColourOrderPair* PostQAPData::_internal_add_colourordering() {
  return colourordering_.Add();
}
inline ::ColourOrderPair* PostQAPData::add_colourordering() {
  // @@protoc_insertion_point(field_add:PostQAPData.colourOrdering)
  return _internal_add_colourordering();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ColourOrderPair >&
PostQAPData::colourordering() const {
  // @@protoc_insertion_point(field_list:PostQAPData.colourOrdering)
  return colourordering_;
}

// -------------------------------------------------------------------

// CartesianCoords

// float x = 1;
inline void CartesianCoords::clear_x() {
  x_ = 0;
}
inline float CartesianCoords::_internal_x() const {
  return x_;
}
inline float CartesianCoords::x() const {
  // @@protoc_insertion_point(field_get:CartesianCoords.x)
  return _internal_x();
}
inline void CartesianCoords::_internal_set_x(float value) {
  
  x_ = value;
}
inline void CartesianCoords::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:CartesianCoords.x)
}

// float y = 2;
inline void CartesianCoords::clear_y() {
  y_ = 0;
}
inline float CartesianCoords::_internal_y() const {
  return y_;
}
inline float CartesianCoords::y() const {
  // @@protoc_insertion_point(field_get:CartesianCoords.y)
  return _internal_y();
}
inline void CartesianCoords::_internal_set_y(float value) {
  
  y_ = value;
}
inline void CartesianCoords::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:CartesianCoords.y)
}

// -------------------------------------------------------------------

// GraphLayout

// repeated .CartesianCoords vertexCoords = 1;
inline int GraphLayout::_internal_vertexcoords_size() const {
  return vertexcoords_.size();
}
inline int GraphLayout::vertexcoords_size() const {
  return _internal_vertexcoords_size();
}
inline void GraphLayout::clear_vertexcoords() {
  vertexcoords_.Clear();
}
inline ::CartesianCoords* GraphLayout::mutable_vertexcoords(int index) {
  // @@protoc_insertion_point(field_mutable:GraphLayout.vertexCoords)
  return vertexcoords_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CartesianCoords >*
GraphLayout::mutable_vertexcoords() {
  // @@protoc_insertion_point(field_mutable_list:GraphLayout.vertexCoords)
  return &vertexcoords_;
}
inline const ::CartesianCoords& GraphLayout::_internal_vertexcoords(int index) const {
  return vertexcoords_.Get(index);
}
inline const ::CartesianCoords& GraphLayout::vertexcoords(int index) const {
  // @@protoc_insertion_point(field_get:GraphLayout.vertexCoords)
  return _internal_vertexcoords(index);
}
inline ::CartesianCoords* GraphLayout::_internal_add_vertexcoords() {
  return vertexcoords_.Add();
}
inline ::CartesianCoords* GraphLayout::add_vertexcoords() {
  // @@protoc_insertion_point(field_add:GraphLayout.vertexCoords)
  return _internal_add_vertexcoords();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CartesianCoords >&
GraphLayout::vertexcoords() const {
  // @@protoc_insertion_point(field_list:GraphLayout.vertexCoords)
  return vertexcoords_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2fcpp_5fto_5fpy_5fbackend_2eproto
