// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: py_to_cpp_backend.proto
#ifndef GRPC_py_5fto_5fcpp_5fbackend_2eproto__INCLUDED
#define GRPC_py_5fto_5fcpp_5fbackend_2eproto__INCLUDED

#include "py_to_cpp_backend.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

class GraphLayoutService final {
 public:
  static constexpr char const* service_full_name() {
    return "GraphLayoutService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status computeGraphLayout(::grpc::ClientContext* context, const ::EdgeList& request, ::GraphLayout* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GraphLayout>> AsynccomputeGraphLayout(::grpc::ClientContext* context, const ::EdgeList& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GraphLayout>>(AsynccomputeGraphLayoutRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GraphLayout>> PrepareAsynccomputeGraphLayout(::grpc::ClientContext* context, const ::EdgeList& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GraphLayout>>(PrepareAsynccomputeGraphLayoutRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void computeGraphLayout(::grpc::ClientContext* context, const ::EdgeList* request, ::GraphLayout* response, std::function<void(::grpc::Status)>) = 0;
      virtual void computeGraphLayout(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::GraphLayout* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void computeGraphLayout(::grpc::ClientContext* context, const ::EdgeList* request, ::GraphLayout* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void computeGraphLayout(::grpc::ClientContext* context, const ::EdgeList* request, ::GraphLayout* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void computeGraphLayout(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::GraphLayout* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void computeGraphLayout(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::GraphLayout* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GraphLayout>* AsynccomputeGraphLayoutRaw(::grpc::ClientContext* context, const ::EdgeList& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GraphLayout>* PrepareAsynccomputeGraphLayoutRaw(::grpc::ClientContext* context, const ::EdgeList& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status computeGraphLayout(::grpc::ClientContext* context, const ::EdgeList& request, ::GraphLayout* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GraphLayout>> AsynccomputeGraphLayout(::grpc::ClientContext* context, const ::EdgeList& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GraphLayout>>(AsynccomputeGraphLayoutRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GraphLayout>> PrepareAsynccomputeGraphLayout(::grpc::ClientContext* context, const ::EdgeList& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GraphLayout>>(PrepareAsynccomputeGraphLayoutRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void computeGraphLayout(::grpc::ClientContext* context, const ::EdgeList* request, ::GraphLayout* response, std::function<void(::grpc::Status)>) override;
      void computeGraphLayout(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::GraphLayout* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void computeGraphLayout(::grpc::ClientContext* context, const ::EdgeList* request, ::GraphLayout* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void computeGraphLayout(::grpc::ClientContext* context, const ::EdgeList* request, ::GraphLayout* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void computeGraphLayout(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::GraphLayout* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void computeGraphLayout(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::GraphLayout* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::GraphLayout>* AsynccomputeGraphLayoutRaw(::grpc::ClientContext* context, const ::EdgeList& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::GraphLayout>* PrepareAsynccomputeGraphLayoutRaw(::grpc::ClientContext* context, const ::EdgeList& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_computeGraphLayout_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status computeGraphLayout(::grpc::ServerContext* context, const ::EdgeList* request, ::GraphLayout* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_computeGraphLayout : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_computeGraphLayout() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_computeGraphLayout() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status computeGraphLayout(::grpc::ServerContext* /*context*/, const ::EdgeList* /*request*/, ::GraphLayout* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcomputeGraphLayout(::grpc::ServerContext* context, ::EdgeList* request, ::grpc::ServerAsyncResponseWriter< ::GraphLayout>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_computeGraphLayout<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_computeGraphLayout : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_computeGraphLayout() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::EdgeList, ::GraphLayout>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::EdgeList* request, ::GraphLayout* response) { return this->computeGraphLayout(context, request, response); }));}
    void SetMessageAllocatorFor_computeGraphLayout(
        ::grpc::experimental::MessageAllocator< ::EdgeList, ::GraphLayout>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::EdgeList, ::GraphLayout>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_computeGraphLayout() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status computeGraphLayout(::grpc::ServerContext* /*context*/, const ::EdgeList* /*request*/, ::GraphLayout* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* computeGraphLayout(
      ::grpc::CallbackServerContext* /*context*/, const ::EdgeList* /*request*/, ::GraphLayout* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* computeGraphLayout(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::EdgeList* /*request*/, ::GraphLayout* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_computeGraphLayout<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_computeGraphLayout<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_computeGraphLayout : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_computeGraphLayout() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_computeGraphLayout() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status computeGraphLayout(::grpc::ServerContext* /*context*/, const ::EdgeList* /*request*/, ::GraphLayout* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_computeGraphLayout : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_computeGraphLayout() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_computeGraphLayout() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status computeGraphLayout(::grpc::ServerContext* /*context*/, const ::EdgeList* /*request*/, ::GraphLayout* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcomputeGraphLayout(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_computeGraphLayout : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_computeGraphLayout() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->computeGraphLayout(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_computeGraphLayout() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status computeGraphLayout(::grpc::ServerContext* /*context*/, const ::EdgeList* /*request*/, ::GraphLayout* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* computeGraphLayout(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* computeGraphLayout(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_computeGraphLayout : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_computeGraphLayout() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::EdgeList, ::GraphLayout>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::EdgeList, ::GraphLayout>* streamer) {
                       return this->StreamedcomputeGraphLayout(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_computeGraphLayout() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status computeGraphLayout(::grpc::ServerContext* /*context*/, const ::EdgeList* /*request*/, ::GraphLayout* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedcomputeGraphLayout(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::EdgeList,::GraphLayout>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_computeGraphLayout<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_computeGraphLayout<Service > StreamedService;
};


#endif  // GRPC_py_5fto_5fcpp_5fbackend_2eproto__INCLUDED
