// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: py_to_cpp_backend.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_py_5fto_5fcpp_5fbackend_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_py_5fto_5fcpp_5fbackend_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_py_5fto_5fcpp_5fbackend_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_py_5fto_5fcpp_5fbackend_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_py_5fto_5fcpp_5fbackend_2eproto;
class CartesianCoord;
class CartesianCoordDefaultTypeInternal;
extern CartesianCoordDefaultTypeInternal _CartesianCoord_default_instance_;
class Edge;
class EdgeDefaultTypeInternal;
extern EdgeDefaultTypeInternal _Edge_default_instance_;
class EdgeList;
class EdgeListDefaultTypeInternal;
extern EdgeListDefaultTypeInternal _EdgeList_default_instance_;
class GraphLayout;
class GraphLayoutDefaultTypeInternal;
extern GraphLayoutDefaultTypeInternal _GraphLayout_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::CartesianCoord* Arena::CreateMaybeMessage<::CartesianCoord>(Arena*);
template<> ::Edge* Arena::CreateMaybeMessage<::Edge>(Arena*);
template<> ::EdgeList* Arena::CreateMaybeMessage<::EdgeList>(Arena*);
template<> ::GraphLayout* Arena::CreateMaybeMessage<::GraphLayout>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Edge PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Edge) */ {
 public:
  inline Edge() : Edge(nullptr) {};
  virtual ~Edge();

  Edge(const Edge& from);
  Edge(Edge&& from) noexcept
    : Edge() {
    *this = ::std::move(from);
  }

  inline Edge& operator=(const Edge& from) {
    CopyFrom(from);
    return *this;
  }
  inline Edge& operator=(Edge&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Edge& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Edge* internal_default_instance() {
    return reinterpret_cast<const Edge*>(
               &_Edge_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Edge& a, Edge& b) {
    a.Swap(&b);
  }
  inline void Swap(Edge* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Edge* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Edge* New() const final {
    return CreateMaybeMessage<Edge>(nullptr);
  }

  Edge* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Edge>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Edge& from);
  void MergeFrom(const Edge& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Edge* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Edge";
  }
  protected:
  explicit Edge(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_py_5fto_5fcpp_5fbackend_2eproto);
    return ::descriptor_table_py_5fto_5fcpp_5fbackend_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSrcVertexIndexFieldNumber = 1,
    kDestVertexIndexFieldNumber = 2,
  };
  // uint32 srcVertexIndex = 1;
  void clear_srcvertexindex();
  ::PROTOBUF_NAMESPACE_ID::uint32 srcvertexindex() const;
  void set_srcvertexindex(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_srcvertexindex() const;
  void _internal_set_srcvertexindex(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 destVertexIndex = 2;
  void clear_destvertexindex();
  ::PROTOBUF_NAMESPACE_ID::uint32 destvertexindex() const;
  void set_destvertexindex(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_destvertexindex() const;
  void _internal_set_destvertexindex(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:Edge)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 srcvertexindex_;
  ::PROTOBUF_NAMESPACE_ID::uint32 destvertexindex_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_py_5fto_5fcpp_5fbackend_2eproto;
};
// -------------------------------------------------------------------

class EdgeList PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:EdgeList) */ {
 public:
  inline EdgeList() : EdgeList(nullptr) {};
  virtual ~EdgeList();

  EdgeList(const EdgeList& from);
  EdgeList(EdgeList&& from) noexcept
    : EdgeList() {
    *this = ::std::move(from);
  }

  inline EdgeList& operator=(const EdgeList& from) {
    CopyFrom(from);
    return *this;
  }
  inline EdgeList& operator=(EdgeList&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EdgeList& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EdgeList* internal_default_instance() {
    return reinterpret_cast<const EdgeList*>(
               &_EdgeList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(EdgeList& a, EdgeList& b) {
    a.Swap(&b);
  }
  inline void Swap(EdgeList* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EdgeList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EdgeList* New() const final {
    return CreateMaybeMessage<EdgeList>(nullptr);
  }

  EdgeList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EdgeList>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EdgeList& from);
  void MergeFrom(const EdgeList& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EdgeList* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "EdgeList";
  }
  protected:
  explicit EdgeList(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_py_5fto_5fcpp_5fbackend_2eproto);
    return ::descriptor_table_py_5fto_5fcpp_5fbackend_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEdgesFieldNumber = 1,
  };
  // repeated .Edge edges = 1;
  int edges_size() const;
  private:
  int _internal_edges_size() const;
  public:
  void clear_edges();
  ::Edge* mutable_edges(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Edge >*
      mutable_edges();
  private:
  const ::Edge& _internal_edges(int index) const;
  ::Edge* _internal_add_edges();
  public:
  const ::Edge& edges(int index) const;
  ::Edge* add_edges();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Edge >&
      edges() const;

  // @@protoc_insertion_point(class_scope:EdgeList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Edge > edges_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_py_5fto_5fcpp_5fbackend_2eproto;
};
// -------------------------------------------------------------------

class CartesianCoord PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CartesianCoord) */ {
 public:
  inline CartesianCoord() : CartesianCoord(nullptr) {};
  virtual ~CartesianCoord();

  CartesianCoord(const CartesianCoord& from);
  CartesianCoord(CartesianCoord&& from) noexcept
    : CartesianCoord() {
    *this = ::std::move(from);
  }

  inline CartesianCoord& operator=(const CartesianCoord& from) {
    CopyFrom(from);
    return *this;
  }
  inline CartesianCoord& operator=(CartesianCoord&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CartesianCoord& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CartesianCoord* internal_default_instance() {
    return reinterpret_cast<const CartesianCoord*>(
               &_CartesianCoord_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(CartesianCoord& a, CartesianCoord& b) {
    a.Swap(&b);
  }
  inline void Swap(CartesianCoord* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CartesianCoord* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CartesianCoord* New() const final {
    return CreateMaybeMessage<CartesianCoord>(nullptr);
  }

  CartesianCoord* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CartesianCoord>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CartesianCoord& from);
  void MergeFrom(const CartesianCoord& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CartesianCoord* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CartesianCoord";
  }
  protected:
  explicit CartesianCoord(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_py_5fto_5fcpp_5fbackend_2eproto);
    return ::descriptor_table_py_5fto_5fcpp_5fbackend_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // @@protoc_insertion_point(class_scope:CartesianCoord)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float x_;
  float y_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_py_5fto_5fcpp_5fbackend_2eproto;
};
// -------------------------------------------------------------------

class GraphLayout PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GraphLayout) */ {
 public:
  inline GraphLayout() : GraphLayout(nullptr) {};
  virtual ~GraphLayout();

  GraphLayout(const GraphLayout& from);
  GraphLayout(GraphLayout&& from) noexcept
    : GraphLayout() {
    *this = ::std::move(from);
  }

  inline GraphLayout& operator=(const GraphLayout& from) {
    CopyFrom(from);
    return *this;
  }
  inline GraphLayout& operator=(GraphLayout&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GraphLayout& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GraphLayout* internal_default_instance() {
    return reinterpret_cast<const GraphLayout*>(
               &_GraphLayout_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(GraphLayout& a, GraphLayout& b) {
    a.Swap(&b);
  }
  inline void Swap(GraphLayout* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GraphLayout* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GraphLayout* New() const final {
    return CreateMaybeMessage<GraphLayout>(nullptr);
  }

  GraphLayout* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GraphLayout>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GraphLayout& from);
  void MergeFrom(const GraphLayout& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GraphLayout* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GraphLayout";
  }
  protected:
  explicit GraphLayout(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_py_5fto_5fcpp_5fbackend_2eproto);
    return ::descriptor_table_py_5fto_5fcpp_5fbackend_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLayoutPositionsFieldNumber = 1,
  };
  // repeated .CartesianCoord layoutPositions = 1;
  int layoutpositions_size() const;
  private:
  int _internal_layoutpositions_size() const;
  public:
  void clear_layoutpositions();
  ::CartesianCoord* mutable_layoutpositions(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CartesianCoord >*
      mutable_layoutpositions();
  private:
  const ::CartesianCoord& _internal_layoutpositions(int index) const;
  ::CartesianCoord* _internal_add_layoutpositions();
  public:
  const ::CartesianCoord& layoutpositions(int index) const;
  ::CartesianCoord* add_layoutpositions();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CartesianCoord >&
      layoutpositions() const;

  // @@protoc_insertion_point(class_scope:GraphLayout)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CartesianCoord > layoutpositions_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_py_5fto_5fcpp_5fbackend_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Edge

// uint32 srcVertexIndex = 1;
inline void Edge::clear_srcvertexindex() {
  srcvertexindex_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Edge::_internal_srcvertexindex() const {
  return srcvertexindex_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Edge::srcvertexindex() const {
  // @@protoc_insertion_point(field_get:Edge.srcVertexIndex)
  return _internal_srcvertexindex();
}
inline void Edge::_internal_set_srcvertexindex(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  srcvertexindex_ = value;
}
inline void Edge::set_srcvertexindex(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_srcvertexindex(value);
  // @@protoc_insertion_point(field_set:Edge.srcVertexIndex)
}

// uint32 destVertexIndex = 2;
inline void Edge::clear_destvertexindex() {
  destvertexindex_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Edge::_internal_destvertexindex() const {
  return destvertexindex_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Edge::destvertexindex() const {
  // @@protoc_insertion_point(field_get:Edge.destVertexIndex)
  return _internal_destvertexindex();
}
inline void Edge::_internal_set_destvertexindex(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  destvertexindex_ = value;
}
inline void Edge::set_destvertexindex(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_destvertexindex(value);
  // @@protoc_insertion_point(field_set:Edge.destVertexIndex)
}

// -------------------------------------------------------------------

// EdgeList

// repeated .Edge edges = 1;
inline int EdgeList::_internal_edges_size() const {
  return edges_.size();
}
inline int EdgeList::edges_size() const {
  return _internal_edges_size();
}
inline void EdgeList::clear_edges() {
  edges_.Clear();
}
inline ::Edge* EdgeList::mutable_edges(int index) {
  // @@protoc_insertion_point(field_mutable:EdgeList.edges)
  return edges_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Edge >*
EdgeList::mutable_edges() {
  // @@protoc_insertion_point(field_mutable_list:EdgeList.edges)
  return &edges_;
}
inline const ::Edge& EdgeList::_internal_edges(int index) const {
  return edges_.Get(index);
}
inline const ::Edge& EdgeList::edges(int index) const {
  // @@protoc_insertion_point(field_get:EdgeList.edges)
  return _internal_edges(index);
}
inline ::Edge* EdgeList::_internal_add_edges() {
  return edges_.Add();
}
inline ::Edge* EdgeList::add_edges() {
  // @@protoc_insertion_point(field_add:EdgeList.edges)
  return _internal_add_edges();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Edge >&
EdgeList::edges() const {
  // @@protoc_insertion_point(field_list:EdgeList.edges)
  return edges_;
}

// -------------------------------------------------------------------

// CartesianCoord

// float x = 1;
inline void CartesianCoord::clear_x() {
  x_ = 0;
}
inline float CartesianCoord::_internal_x() const {
  return x_;
}
inline float CartesianCoord::x() const {
  // @@protoc_insertion_point(field_get:CartesianCoord.x)
  return _internal_x();
}
inline void CartesianCoord::_internal_set_x(float value) {
  
  x_ = value;
}
inline void CartesianCoord::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:CartesianCoord.x)
}

// float y = 2;
inline void CartesianCoord::clear_y() {
  y_ = 0;
}
inline float CartesianCoord::_internal_y() const {
  return y_;
}
inline float CartesianCoord::y() const {
  // @@protoc_insertion_point(field_get:CartesianCoord.y)
  return _internal_y();
}
inline void CartesianCoord::_internal_set_y(float value) {
  
  y_ = value;
}
inline void CartesianCoord::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:CartesianCoord.y)
}

// -------------------------------------------------------------------

// GraphLayout

// repeated .CartesianCoord layoutPositions = 1;
inline int GraphLayout::_internal_layoutpositions_size() const {
  return layoutpositions_.size();
}
inline int GraphLayout::layoutpositions_size() const {
  return _internal_layoutpositions_size();
}
inline void GraphLayout::clear_layoutpositions() {
  layoutpositions_.Clear();
}
inline ::CartesianCoord* GraphLayout::mutable_layoutpositions(int index) {
  // @@protoc_insertion_point(field_mutable:GraphLayout.layoutPositions)
  return layoutpositions_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CartesianCoord >*
GraphLayout::mutable_layoutpositions() {
  // @@protoc_insertion_point(field_mutable_list:GraphLayout.layoutPositions)
  return &layoutpositions_;
}
inline const ::CartesianCoord& GraphLayout::_internal_layoutpositions(int index) const {
  return layoutpositions_.Get(index);
}
inline const ::CartesianCoord& GraphLayout::layoutpositions(int index) const {
  // @@protoc_insertion_point(field_get:GraphLayout.layoutPositions)
  return _internal_layoutpositions(index);
}
inline ::CartesianCoord* GraphLayout::_internal_add_layoutpositions() {
  return layoutpositions_.Add();
}
inline ::CartesianCoord* GraphLayout::add_layoutpositions() {
  // @@protoc_insertion_point(field_add:GraphLayout.layoutPositions)
  return _internal_add_layoutpositions();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CartesianCoord >&
GraphLayout::layoutpositions() const {
  // @@protoc_insertion_point(field_list:GraphLayout.layoutPositions)
  return layoutpositions_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_py_5fto_5fcpp_5fbackend_2eproto
