// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: py_to_cpp_backend.proto

#include "py_to_cpp_backend.pb.h"
#include "py_to_cpp_backend.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* GraphLayoutService_method_names[] = {
  "/GraphLayoutService/computeGraphLayout",
};

std::unique_ptr< GraphLayoutService::Stub> GraphLayoutService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GraphLayoutService::Stub> stub(new GraphLayoutService::Stub(channel));
  return stub;
}

GraphLayoutService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_computeGraphLayout_(GraphLayoutService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status GraphLayoutService::Stub::computeGraphLayout(::grpc::ClientContext* context, const ::EdgeList& request, ::GraphLayout* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_computeGraphLayout_, context, request, response);
}

void GraphLayoutService::Stub::experimental_async::computeGraphLayout(::grpc::ClientContext* context, const ::EdgeList* request, ::GraphLayout* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_computeGraphLayout_, context, request, response, std::move(f));
}

void GraphLayoutService::Stub::experimental_async::computeGraphLayout(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::GraphLayout* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_computeGraphLayout_, context, request, response, std::move(f));
}

void GraphLayoutService::Stub::experimental_async::computeGraphLayout(::grpc::ClientContext* context, const ::EdgeList* request, ::GraphLayout* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_computeGraphLayout_, context, request, response, reactor);
}

void GraphLayoutService::Stub::experimental_async::computeGraphLayout(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::GraphLayout* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_computeGraphLayout_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GraphLayout>* GraphLayoutService::Stub::AsynccomputeGraphLayoutRaw(::grpc::ClientContext* context, const ::EdgeList& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::GraphLayout>::Create(channel_.get(), cq, rpcmethod_computeGraphLayout_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::GraphLayout>* GraphLayoutService::Stub::PrepareAsynccomputeGraphLayoutRaw(::grpc::ClientContext* context, const ::EdgeList& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::GraphLayout>::Create(channel_.get(), cq, rpcmethod_computeGraphLayout_, context, request, false);
}

GraphLayoutService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GraphLayoutService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GraphLayoutService::Service, ::EdgeList, ::GraphLayout>(
          [](GraphLayoutService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::EdgeList* req,
             ::GraphLayout* resp) {
               return service->computeGraphLayout(ctx, req, resp);
             }, this)));
}

GraphLayoutService::Service::~Service() {
}

::grpc::Status GraphLayoutService::Service::computeGraphLayout(::grpc::ServerContext* context, const ::EdgeList* request, ::GraphLayout* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


