# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import cpp_to_py_backend_pb2 as proto_dot_cpp__to__py__backend__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/cpp_to_py_backend_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GraphLayoutServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.performPreQAPComputations = channel.unary_unary(
                '/GraphLayoutService/performPreQAPComputations',
                request_serializer=proto_dot_cpp__to__py__backend__pb2.EdgeList.SerializeToString,
                response_deserializer=proto_dot_cpp__to__py__backend__pb2.PreQAPData.FromString,
                _registered_method=True)
        self.performPostQAPComputations = channel.unary_unary(
                '/GraphLayoutService/performPostQAPComputations',
                request_serializer=proto_dot_cpp__to__py__backend__pb2.PostQAPData.SerializeToString,
                response_deserializer=proto_dot_cpp__to__py__backend__pb2.GraphLayout.FromString,
                _registered_method=True)


class GraphLayoutServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def performPreQAPComputations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def performPostQAPComputations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraphLayoutServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'performPreQAPComputations': grpc.unary_unary_rpc_method_handler(
                    servicer.performPreQAPComputations,
                    request_deserializer=proto_dot_cpp__to__py__backend__pb2.EdgeList.FromString,
                    response_serializer=proto_dot_cpp__to__py__backend__pb2.PreQAPData.SerializeToString,
            ),
            'performPostQAPComputations': grpc.unary_unary_rpc_method_handler(
                    servicer.performPostQAPComputations,
                    request_deserializer=proto_dot_cpp__to__py__backend__pb2.PostQAPData.FromString,
                    response_serializer=proto_dot_cpp__to__py__backend__pb2.GraphLayout.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GraphLayoutService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('GraphLayoutService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GraphLayoutService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def performPreQAPComputations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GraphLayoutService/performPreQAPComputations',
            proto_dot_cpp__to__py__backend__pb2.EdgeList.SerializeToString,
            proto_dot_cpp__to__py__backend__pb2.PreQAPData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def performPostQAPComputations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GraphLayoutService/performPostQAPComputations',
            proto_dot_cpp__to__py__backend__pb2.PostQAPData.SerializeToString,
            proto_dot_cpp__to__py__backend__pb2.GraphLayout.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
