# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: py_to_cpp_backend.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'py_to_cpp_backend.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17py_to_cpp_backend.proto\"7\n\x04\x45\x64ge\x12\x16\n\x0esrcVertexIndex\x18\x01 \x01(\r\x12\x17\n\x0f\x64\x65stVertexIndex\x18\x02 \x01(\r\" \n\x08\x45\x64geList\x12\x14\n\x05\x65\x64ges\x18\x01 \x03(\x0b\x32\x05.Edge\"&\n\x0e\x43\x61rtesianCoord\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"7\n\x0bGraphLayout\x12(\n\x0flayoutPositions\x18\x01 \x03(\x0b\x32\x0f.CartesianCoord2E\n\x12GraphLayoutService\x12/\n\x12\x63omputeGraphLayout\x12\t.EdgeList\x1a\x0c.GraphLayout\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'py_to_cpp_backend_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EDGE']._serialized_start=27
  _globals['_EDGE']._serialized_end=82
  _globals['_EDGELIST']._serialized_start=84
  _globals['_EDGELIST']._serialized_end=116
  _globals['_CARTESIANCOORD']._serialized_start=118
  _globals['_CARTESIANCOORD']._serialized_end=156
  _globals['_GRAPHLAYOUT']._serialized_start=158
  _globals['_GRAPHLAYOUT']._serialized_end=213
  _globals['_GRAPHLAYOUTSERVICE']._serialized_start=215
  _globals['_GRAPHLAYOUTSERVICE']._serialized_end=284
# @@protoc_insertion_point(module_scope)
